using SimRacingSdk.Ams2.Core.Abstractions;
using SimRacingSdk.Ams2.Core.Enums;
using SimRacingSdk.Ams2.Core.Models;

namespace SimRacingSdk.Ams2.Core;

public class Ams2NationalityInfoProvider : IAms2NationalityInfoProvider
{
    private static Ams2NationalityInfoProvider? singletonInstance;

    public List<Ams2NationalityInfo> Nationalities =
    [
        new(Ams2Nationality.None, "Any", "ZZZ"),
        new(Ams2Nationality.Afghanistan, "Afghanistan", "AFG"),
        new(Ams2Nationality.Albania, "Albania", "ALB"),
        new(Ams2Nationality.Algeria, "Algeria", "DZA"),
        new(Ams2Nationality.Andorra, "Andorra", "AND"),
        new(Ams2Nationality.Angola, "Angola", "AGO"),
        new(Ams2Nationality.AntiguaAndDeps, "Antigua and Deps", "ATG"),
        new(Ams2Nationality.Argentina, "Argentina", "ARG"),
        new(Ams2Nationality.Armenia, "Armenia", "ARM"),
        new(Ams2Nationality.Australia, "Australia", "AUS"),
        new(Ams2Nationality.Austria, "Austria", "AUT"),
        new(Ams2Nationality.Azerbaijan, "Azerbaijan", "AZE"),
        new(Ams2Nationality.Bahamas, "Bahamas", "BHS"),
        new(Ams2Nationality.Bahrain, "Bahrain", "BHR"),
        new(Ams2Nationality.Bangladesh, "Bangladesh", "BGD"),
        new(Ams2Nationality.Barbados, "Barbados", "BRB"),
        new(Ams2Nationality.Belarus, "Belarus", "BLR"),
        new(Ams2Nationality.Belgium, "Belgium", "BEL"),
        new(Ams2Nationality.Belize, "Belize", "BLZ"),
        new(Ams2Nationality.Benin, "Benin", "BEN"),
        new(Ams2Nationality.Bhutan, "Bhutan", "BTN"),
        new(Ams2Nationality.Bolivia, "Bolivia", "BOL"),
        new(Ams2Nationality.BosniaHerzegovina, "Bosnia Herzegovina", "BIH"),
        new(Ams2Nationality.Botswana, "Botswana", "BWA"),
        new(Ams2Nationality.Brazil, "Brazil", "BRA"),
        new(Ams2Nationality.Brunei, "Brunei", "BRN"),
        new(Ams2Nationality.Bulgaria, "Bulgaria", "BGR"),
        new(Ams2Nationality.Burkina, "Burkina", "BFA"),
        new(Ams2Nationality.Burundi, "Burundi", "BDI"),
        new(Ams2Nationality.Cambodia, "Cambodia", "KHM"),
        new(Ams2Nationality.Cameroon, "Cameroon", "CMR"),
        new(Ams2Nationality.Canada, "Canada", "CAN"),
        new(Ams2Nationality.CapeVerde, "CapeVerde", "CBV"),
        new(Ams2Nationality.CentralAfricanRepublic, "Central African Republic", "CAF"),
        new(Ams2Nationality.Chad, "Chad", "TCD"),
        new(Ams2Nationality.Chile, "Chile", "CHL"),
        new(Ams2Nationality.China, "China", "CHN"),
        new(Ams2Nationality.Columbia, "Columbia", "COL"),
        new(Ams2Nationality.Comoros, "Comoros", "COM"),
        new(Ams2Nationality.Congo, "Congo", "COG"),
        new(Ams2Nationality.CongoDemocraticRepublic, "Democratic Republic of Congo", "COD"),
        new(Ams2Nationality.CostaRica, "Costa Rica", "CRI"),
        new(Ams2Nationality.Croatia, "Croatia", "HRV"),
        new(Ams2Nationality.Cuba, "Cuba", "CUB"),
        new(Ams2Nationality.Cyprus, "Cyprus", "CYP"),
        new(Ams2Nationality.CzechRepublic, "Czech Republic", "CZE"),
        new(Ams2Nationality.Denmark, "Denmark", "DNK"),
        new(Ams2Nationality.Djibouti, "Djibouti", "DJI"),
        new(Ams2Nationality.Dominica, "Dominica", "DMA"),
        new(Ams2Nationality.DominicanRepublic, "Dominican Republic", "DOM"),
        new(Ams2Nationality.EastTimor, "East Timor", "TLS"),
        new(Ams2Nationality.Ecuador, "Ecuador", "ECU"),
        new(Ams2Nationality.Egypt, "Egypt", "EGY"),
        new(Ams2Nationality.ElSalvador, "El Salvador", "SLV"),
        new(Ams2Nationality.EquatorialGuinea, "Equatorial Guinea", "GNQ"),
        new(Ams2Nationality.Eritrea, "Eritrea", "ERI"),
        new(Ams2Nationality.Estonia, "Estonia", "EST"),
        new(Ams2Nationality.Ethiopia, "Ethiopia", "ETH"),
        new(Ams2Nationality.Fiji, "Fiji", "FJI"),
        new(Ams2Nationality.Finland, "Finland", "FIN"),
        new(Ams2Nationality.France, "France", "FRA"),
        new(Ams2Nationality.Gabon, "Gabon", "GAB"),
        new(Ams2Nationality.Gambia, "Gambia", "GMB"),
        new(Ams2Nationality.Georgia, "Georgia", "GEO"),
        new(Ams2Nationality.Germany, "Germany", "DEU"),
        new(Ams2Nationality.Ghana, "Ghana", "GHA"),
        new(Ams2Nationality.Greece, "Greece", "GRC"),
        new(Ams2Nationality.Grenada, "Grenada", "GRD"),
        new(Ams2Nationality.Guatemala, "Guatemala", "GTM"),
        new(Ams2Nationality.Guinea, "Guinea", "GIN"),
        new(Ams2Nationality.GuineaBissau, "Guinea Bissau", "GNB"),
        new(Ams2Nationality.Guyana, "Guyana", "GUY"),
        new(Ams2Nationality.Haiti, "Haiti", "HTI"),
        new(Ams2Nationality.Honduras, "Honduras", "HND"),
        new(Ams2Nationality.HongKong, "Hong Kong", "HKG"),
        new(Ams2Nationality.Hungary, "Hungary", "HUN"),
        new(Ams2Nationality.Iceland, "Iceland", "ISL"),
        new(Ams2Nationality.India, "India", "IND"),
        new(Ams2Nationality.Indonesia, "Indonesia", "IDN"),
        new(Ams2Nationality.Iran, "Iran", "IRN"),
        new(Ams2Nationality.Iraq, "Iraq", "IRQ"),
        new(Ams2Nationality.Israel, "Israel", "ISR"),
        new(Ams2Nationality.Italy, "Italy", "ITA"),
        new(Ams2Nationality.IvoryCoast, "Ivory Coast", "CIV"),
        new(Ams2Nationality.Jamaica, "Jamaica", "JAM"),
        new(Ams2Nationality.Japan, "Japan", "JPN"),
        new(Ams2Nationality.Jordan, "Jordan", "JOR"),
        new(Ams2Nationality.Kazakhstan, "Kazakhstan", "KAZ"),
        new(Ams2Nationality.Kenya, "Kenya", "KEN"),
        new(Ams2Nationality.Kiribati, "Kiribati", "KIR"),
        new(Ams2Nationality.Kosovo, "Kosovo", "XKX"),
        new(Ams2Nationality.Kuwait, "Kuwait", "KWT"),
        new(Ams2Nationality.Kyrgyzstan, "Kyrgyzstan", "KGZ"),
        new(Ams2Nationality.Laos, "Laos", "LAO"),
        new(Ams2Nationality.Latvia, "Latvia", "LVA"),
        new(Ams2Nationality.Lebanon, "Lebanon", "LBN"),
        new(Ams2Nationality.Lesotho, "Lesotho", "LSO"),
        new(Ams2Nationality.Liberia, "Liberia", "LBR"),
        new(Ams2Nationality.Libya, "Libya", "LBY"),
        new(Ams2Nationality.Liechtenstein, "Liechtenstein", "LIE"),
        new(Ams2Nationality.Lithuania, "Lithuania", "LTU"),
        new(Ams2Nationality.Luxembourg, "Luxembourg", "LUX"),
        new(Ams2Nationality.Macedonia, "Macedonia", "MAC"),
        new(Ams2Nationality.Madagascar, "Madagascar", "MDG"),
        new(Ams2Nationality.Malawi, "Malawi", "MWI"),
        new(Ams2Nationality.Malaysia, "Malaysia", "MYS"),
        new(Ams2Nationality.Mali, "Mali", "MLI"),
        new(Ams2Nationality.Malta, "Malta", "MLT"),
        new(Ams2Nationality.MarshallIslands, "Marshall Islands", "MHL"),
        new(Ams2Nationality.Mauritania, "Mauritania", "MRT"),
        new(Ams2Nationality.Mauritius, "Mauritius", "MUS"),
        new(Ams2Nationality.Mexico, "Mexico", "MEX"),
        new(Ams2Nationality.Micronesia, "Micronesia", "FSM"),
        new(Ams2Nationality.Moldova, "Moldova", "MDA"),
        new(Ams2Nationality.Monaco, "Monaco", "MCO"),
        new(Ams2Nationality.Mongolia, "Mongolia", "MNG"),
        new(Ams2Nationality.Montenegro, "Montenegro", "MNE"),
        new(Ams2Nationality.Morocco, "Morocco", "MAR"),
        new(Ams2Nationality.Mozambique, "Mozambique", "MOZ"),
        new(Ams2Nationality.Myanmar, "Myanmar", "MMR"),
        new(Ams2Nationality.Namibia, "Namibia", "NAM"),
        new(Ams2Nationality.Nauru, "Nauru", "NRU"),
        new(Ams2Nationality.Nepal, "Nepal", "NPL"),
        new(Ams2Nationality.Netherlands, "Netherlands", "NLD"),
        new(Ams2Nationality.NewZealand, "New Zealand", "NZL"),
        new(Ams2Nationality.Nicaragua, "Nicaragua", "NIC"),
        new(Ams2Nationality.Niger, "Niger", "NER"),
        new(Ams2Nationality.Nigeria, "Nigeria", "NGA"),
        new(Ams2Nationality.NorthKorea, "North Korea", "PRK"),
        new(Ams2Nationality.Norway, "Norway", "NOR"),
        new(Ams2Nationality.Oman, "Oman", "OMN"),
        new(Ams2Nationality.Pakistan, "Pakistan", "PAK"),
        new(Ams2Nationality.Palau, "Palau", "PLW"),
        new(Ams2Nationality.Panama, "Panama", "PAN"),
        new(Ams2Nationality.PapuaNewGuinea, "Papua New Guinea", "PNG"),
        new(Ams2Nationality.Paraguay, "Paraguay", "PRY"),
        new(Ams2Nationality.Peru, "Peru", "PER"),
        new(Ams2Nationality.Philippines, "Philippines", "PHL"),
        new(Ams2Nationality.Poland, "Poland", "POL"),
        new(Ams2Nationality.Portugal, "Portugal", "PRT"),
        new(Ams2Nationality.Qatar, "Qatar", "QAT"),
        new(Ams2Nationality.RepublicOfIreland, "Republic Of Ireland", "IRL"),
        new(Ams2Nationality.Romania, "Romania", "ROU"),
        new(Ams2Nationality.RussianFederation, "Russian Federation", "RUS"),
        new(Ams2Nationality.Rwanda, "Rwanda", "RWA"),
        new(Ams2Nationality.SaintVincentAndTheGrenadines, "Saint Vincent and the Grenadines", "VCT"),
        new(Ams2Nationality.Samoa, "Samoa", "WSM"),
        new(Ams2Nationality.SanMarino, "San Marino", "SMR"),
        new(Ams2Nationality.SaoTomeAndPrincipe, "Sao Tome and Principe", "STP"),
        new(Ams2Nationality.SaudiArabia, "Saudi Arabia", "SAU"),
        new(Ams2Nationality.Senegal, "Senegal", "SEN"),
        new(Ams2Nationality.Serbia, "Serbia", "SRB"),
        new(Ams2Nationality.Seychelles, "Seychelles", "SYC"),
        new(Ams2Nationality.SierraLeone, "Sierra Leone", "SLE"),
        new(Ams2Nationality.Singapore, "Singapore", "SGP"),
        new(Ams2Nationality.Slovakia, "Slovakia", "SVK"),
        new(Ams2Nationality.Slovenia, "Slovenia", "SVN"),
        new(Ams2Nationality.SolomonIslands, "Solomon Islands", "SLB"),
        new(Ams2Nationality.Somalia, "Somalia", "SOM"),
        new(Ams2Nationality.SouthAfrica, "South Africa", "ZAF"),
        new(Ams2Nationality.SouthKorea, "South Korea", "KOR"),
        new(Ams2Nationality.SouthSudan, "South Sudan", "SSD"),
        new(Ams2Nationality.Spain, "Spain", "ESP"),
        new(Ams2Nationality.SriLanka, "Sri Lanka", "LKA"),
        new(Ams2Nationality.StKittsAndNevis, "St. Kitts and Nevis", "KNA"),
        new(Ams2Nationality.StLucia, "St. Lucia", "LCA"),
        new(Ams2Nationality.Sudan, "Sudan", "SDN"),
        new(Ams2Nationality.Suriname, "Suriname", "SUR"),
        new(Ams2Nationality.Swaziland, "Swaziland", "SWZ"),
        new(Ams2Nationality.Sweden, "Sweden", "SWE"),
        new(Ams2Nationality.Switzerland, "Switzerland", "CHE"),
        new(Ams2Nationality.Syria, "Syria", "SYR"),
        new(Ams2Nationality.Taiwan, "Taiwan", "TWN"),
        new(Ams2Nationality.Tajikistan, "Tajikistan", "TJK"),
        new(Ams2Nationality.Tanzania, "Tanzania", "TZA"),
        new(Ams2Nationality.Thailand, "Thailand", "THA"),
        new(Ams2Nationality.Togo, "Togo", "TGO"),
        new(Ams2Nationality.Tonga, "Tonga", "TON"),
        new(Ams2Nationality.TrinidadAndTobago, "Trinidad and Tobago", "TTO"),
        new(Ams2Nationality.Tunisia, "Tunisia", "TUN"),
        new(Ams2Nationality.Turkey, "Turkey", "TUR"),
        new(Ams2Nationality.Turkmenistan, "Turkmenistan", "TKM"),
        new(Ams2Nationality.Tuvalu, "Tuvalu", "TUV"),
        new(Ams2Nationality.Uganda, "Uganda", "UGA"),
        new(Ams2Nationality.Ukraine, "Ukraine", "UKR"),
        new(Ams2Nationality.UnitedArabEmirates, "United Arab Emirates", "ARE"),
        new(Ams2Nationality.UnitedKingdom, "United Kingdom", "GBR"),
        new(Ams2Nationality.UnitedStates, "United States", "USA"),
        new(Ams2Nationality.Uruguay, "Uruguay", "URY"),
        new(Ams2Nationality.Vanuatu, "Vanuatu", "VUT"),
        new(Ams2Nationality.VaticanCity, "Vatican City", "VAT"),
        new(Ams2Nationality.Venezuela, "Venezuela", "VEN"),
        new(Ams2Nationality.Vietnam, "Vietnam", "VNM"),
        new(Ams2Nationality.Yemen, "Yemen", "YEM"),
        new(Ams2Nationality.Zambia, "Zambia", "ZMB"),
        new(Ams2Nationality.Zimbabwe, "Zimbabwe", "ZWE")
    ];

    public static Ams2NationalityInfoProvider Instance =>
        singletonInstance ??= new Ams2NationalityInfoProvider();

    public Ams2NationalityInfo? FindById(Ams2Nationality accNationality)
    {
        return this.Nationalities.FirstOrDefault(n => n.Ams2Nationality == accNationality);
    }

    public string GetCountryCode(Ams2Nationality accNationality)
    {
        return this.FindById(accNationality)
                   ?.CountryCode ?? "ZZZ";
    }
}