using System.Collections.ObjectModel;
using SimRacingSdk.Ams2.Core.Abstractions;
using SimRacingSdk.Ams2.Core.Models;

namespace SimRacingSdk.Ams2.Core;

public class Ams2CarInfoProvider : IAms2CarInfoProvider
{
    private const string DrivelineFwd = "FWD";
    private const string DrivelineRwd = "RWD";
    private const string EngineFlat12 = "Flat 12";
    private const string EngineFlat4 = "Flat 4";
    private const string EnginePlacementFront = "Front";
    private const string EnginePlacementMid = "Mid";
    private const string EnginePlacementMidFront = "Mid-Front";
    private const string EnginePlacementMidRear = "Mid-Rear";
    private const string EnginePlacementRear = "Rear";
    private const string EngineStraight4 = "Straight 4";
    private const string EngineStraight6 = "Straight 6";
    private const string EngineV10 = "V10";
    private const string EngineV12 = "V12";
    private const string EngineV6 = "V6";
    private const string EngineV8 = "V8";
    private const string Transmission4SpeedHPattern = "4 Speed H-Pattern";
    private const string Transmission4SpeedSequential = "4 Speed Sequential";
    private const string Transmission5SpeedHPattern = "5 Speed H-Pattern";
    private const string Transmission5SpeedSequential = "5 Speed Sequential";
    private const string Transmission6SpeedHPattern = "6 Speed H-Pattern";
    private const string Transmission6SpeedSequential = "6 Speed Sequential";
    private const string Transmission7SpeedSequential = "7 Speed Sequential";
    private const string Transmission8SpeedSequential = "8 Speed Sequential";

    private static Ams2CarInfoProvider? singletonInstance;

    private readonly List<Ams2CarInfo> cars =
    [
        new()
        {
            Class = "ARC",
            Differential = "NA",
            DisplacementL = 1.3,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementMidFront,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Chevrolet",
            Model = "ARC Camaro",
            PowerHp = 122,
            TopSpeedKph = 220,
            TorqueNm = 118,
            Transmission = Transmission5SpeedSequential,
            WeightDistribution = "53.0/47.0",
            WeightKg = 595,
            WheelBaseM = 1.84
        },
        new()
        {
            Class = "Caterham",
            Differential = "NA",
            DisplacementL = 2.0,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementMidFront,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = true,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Caterham",
            Model = "Caterham 620R",
            PowerHp = 300,
            TopSpeedKph = 262,
            TorqueNm = 282,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "48.0/52.0",
            WeightKg = 656,
            WheelBaseM = 2.22
        },
        new()
        {
            Class = "Caterham",
            Differential = "NA",
            DisplacementL = 1.6,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementMidFront,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = true,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Caterham",
            Model = "Caterham Academy",
            PowerHp = 121,
            TopSpeedKph = 188,
            TorqueNm = 158,
            Transmission = Transmission5SpeedSequential,
            WeightDistribution = "47.8/52.2",
            WeightKg = 620,
            WheelBaseM = 2.22
        },
        new()
        {
            Class = "Caterham",
            Differential = "NA",
            DisplacementL = 2.0,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementMidFront,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Caterham",
            Model = "Caterham Superlight",
            PowerHp = 177,
            TopSpeedKph = 215,
            TorqueNm = 175,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "48.0/52.0",
            WeightKg = 630,
            WheelBaseM = 2.22
        },
        new()
        {
            Class = "Caterham",
            Differential = "NA",
            DisplacementL = 1.6,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementMidFront,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = true,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Caterham",
            Model = "Caterham Academy",
            PowerHp = 122,
            TopSpeedKph = 190,
            TorqueNm = 162,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "48.0/52.2",
            WeightKg = 600,
            WheelBaseM = 2.22
        },
        new()
        {
            Class = "Copa Classic B",
            Differential = "NA",
            DisplacementL = 1.6,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementFront,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = true,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Chevrolet",
            Model = "Chevrolet Chevette",
            PowerHp = 123,
            TopSpeedKph = 191,
            TorqueNm = 125,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "53.8/46.2",
            WeightKg = 900,
            WheelBaseM = 2.4
        },
        new()
        {
            Class = "Copa Classic B",
            Differential = "NA",
            DisplacementL = 1.6,
            Driveline = DrivelineFwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementFront,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = true,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Gol Classic B",
            PowerHp = 120,
            TopSpeedKph = 190,
            TorqueNm = 123,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "62.8/37.2",
            WeightKg = 880,
            WheelBaseM = 2.37
        },
        new()
        {
            Class = "Copa Classic B",
            Differential = "NA",
            DisplacementL = 1.27,
            Driveline = DrivelineFwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementFront,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = true,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "MINI",
            Model = "MINI Cooper S 1965 B",
            PowerHp = 117,
            TopSpeedKph = 180,
            TorqueNm = 149,
            Transmission = Transmission4SpeedHPattern,
            WeightDistribution = "61.0/39.0",
            WeightKg = 700,
            WheelBaseM = 2.03
        },
        new()
        {
            Class = "Copa Classic B",
            Differential = "NA",
            DisplacementL = 1.27,
            Driveline = DrivelineFwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementFront,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = true,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "MINI",
            Model = "MINI Cooper S 1965 B",
            PowerHp = 117,
            TopSpeedKph = 180,
            TorqueNm = 149,
            Transmission = Transmission4SpeedHPattern,
            WeightDistribution = "61.0/39.0",
            WeightKg = 700,
            WheelBaseM = 2.03
        },
        new()
        {
            Class = "Copa Classic B",
            Differential = "NA",
            DisplacementL = 1.6,
            Driveline = DrivelineFwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementFront,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = true,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Passat Classic B",
            PowerHp = 120,
            TopSpeedKph = 185,
            TorqueNm = 123,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "62.8/37.2",
            WeightKg = 920,
            WheelBaseM = 2.43
        },
        new()
        {
            Class = "Copa Classic B",
            Differential = "NA",
            DisplacementL = 1.6,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineFlat4,
            EnginePlacement = EnginePlacementFront,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = true,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Puma",
            Model = "Puma GTE",
            PowerHp = 123,
            TopSpeedKph = 190,
            TorqueNm = 131,
            Transmission = Transmission4SpeedHPattern,
            WeightDistribution = "42.0/58.0",
            WeightKg = 900,
            WheelBaseM = 2.15
        },
        new()
        {
            Class = "Copa Classic B",
            Differential = "NA",
            DisplacementL = 1.6,
            Driveline = DrivelineFwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementFront,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = true,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Uno Classic B",
            PowerHp = 127,
            TopSpeedKph = 190,
            TorqueNm = 130,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "62.8/37.2",
            WeightKg = 860,
            WheelBaseM = 2.35
        },
        new()
        {
            Class = "Copa Classic FL",
            Differential = "NA",
            DisplacementL = 1.8,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Fusca Classic FL",
            PowerHp = 165,
            TopSpeedKph = 205,
            TorqueNm = 211,
            Transmission = Transmission4SpeedHPattern,
            WeightDistribution = "39.6/60.4",
            WeightKg = 840,
            WheelBaseM = 2.4
        },
        new()
        {
            Class = "Copa Classic FL",
            Differential = "NA",
            DisplacementL = 2,
            Driveline = DrivelineFwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementFront,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = true,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Gol Classic FL",
            PowerHp = 173,
            TopSpeedKph = 205,
            TorqueNm = 220,
            Transmission = Transmission4SpeedHPattern,
            WeightDistribution = "62.8/37.2",
            WeightKg = 880,
            WheelBaseM = 2.37
        },
        new()
        {
            Class = "Copa Classic FL",
            Differential = "NA",
            DisplacementL = 2,
            Driveline = DrivelineFwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementFront,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = true,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Passat Classic FL",
            PowerHp = 173,
            TopSpeedKph = 190,
            TorqueNm = 220,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "62.8/37.2",
            WeightKg = 925,
            WheelBaseM = 2.43
        },
        new()
        {
            Class = "Copa Classic FL",
            Differential = "NA",
            DisplacementL = 4.1,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight6,
            EnginePlacement = EnginePlacementFront,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = true,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Puma",
            Model = "Puma GTB",
            PowerHp = 212,
            TopSpeedKph = 235,
            TorqueNm = 319,
            Transmission = Transmission4SpeedHPattern,
            WeightDistribution = "54.2/45.8",
            WeightKg = 1080,
            WheelBaseM = 2.38
        },
        new()
        {
            Class = "Fusca",
            Differential = "NA",
            DisplacementL = 1.6,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Copa Fusca",
            PowerHp = 123,
            TopSpeedKph = 185,
            TorqueNm = 131,
            Transmission = Transmission4SpeedHPattern,
            WeightDistribution = "40.0/60.0",
            WeightKg = 830,
            WheelBaseM = 2.4
        },
        new()
        {
            Class = "Copa Montana",
            Differential = "NA",
            DisplacementL = 5.7,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidFront,
            HasAdjustableTurbo = false,
            HasBoostButton = true,
            HasDrs = false,
            HasHeadlights = true,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Chevrolet",
            Model = "Copa Montana",
            PowerHp = 369,
            TopSpeedKph = 245,
            TorqueNm = 499,
            Transmission = Transmission5SpeedSequential,
            WeightDistribution = "50.6/49.4",
            WeightKg = 1360,
            WheelBaseM = 2.66
        },
        new()
        {
            Class = "Copa Truck",
            Differential = "NA",
            DisplacementL = 12.9,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight6,
            EnginePlacement = EnginePlacementMidFront,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Iveco",
            Model = "Iveco Stralis",
            PowerHp = 1230,
            TopSpeedKph = 245,
            TorqueNm = 3700,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "56.2/43.8",
            WeightKg = 4800,
            WheelBaseM = 3.30
        },
        new()
        {
            Class = "Copa Truck",
            Differential = "NA",
            DisplacementL = 12.4,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight6,
            EnginePlacement = EnginePlacementMidFront,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Man",
            Model = "Man TGX",
            PowerHp = 1210,
            TopSpeedKph = 245,
            TorqueNm = 3700,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "55.8/44.2",
            WeightKg = 4820,
            WheelBaseM = 3.35
        },
        new()
        {
            Class = "Copa Truck",
            Differential = "NA",
            DisplacementL = 12.8,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight6,
            EnginePlacement = EnginePlacementMidFront,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Mercedes",
            Model = "Mercedes-Benz Actros",
            PowerHp = 1290,
            TopSpeedKph = 245,
            TorqueNm = 3850,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "53.8/46.2",
            WeightKg = 4950,
            WheelBaseM = 3.30
        },
        new()
        {
            Class = "Copa Truck",
            Differential = "NA",
            DisplacementL = 9.4,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight6,
            EnginePlacement = EnginePlacementMidFront,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Volkswagen",
            Model = "Volkswagen Constellation",
            PowerHp = 1150,
            TopSpeedKph = 245,
            TorqueNm = 3500,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "55.8/44.2",
            WeightKg = 4820,
            WheelBaseM = 3.35
        },
        new()
        {
            Class = "Copa Truck",
            Differential = "NA",
            DisplacementL = 12.0,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight6,
            EnginePlacement = EnginePlacementMidFront,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Vulcan Truck",
            PowerHp = 1200,
            TopSpeedKph = 245,
            TorqueNm = 3650,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "55.8/44.2",
            WeightKg = 4900,
            WheelBaseM = 3.35
        },
        new()
        {
            Class = "Copa Uno",
            Differential = "NA",
            DisplacementL = 1.6,
            Driveline = DrivelineFwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementFront,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = true,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Copa Uno",
            PowerHp = 120,
            TopSpeedKph = 190,
            TorqueNm = 175,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "61.8/38.2",
            WeightKg = 860,
            WheelBaseM = 2.35
        },
        new()
        {
            Class = "Formula HiTech",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "TC",
            Engine = EngineV12,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula HiTech Gen 1 Model1",
            PowerHp = 727,
            TopSpeedKph = 335,
            TorqueNm = 378,
            Transmission = Transmission7SpeedSequential,
            WeightDistribution = "42.2/57.8",
            WeightKg = 610,
            WheelBaseM = 2.88
        },
        new()
        {
            Class = "Formula HiTech",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "TC",
            Engine = EngineV10,
            EnginePlacement = EnginePlacementMid,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula HiTech Gen 1 Model2",
            PowerHp = 707,
            TopSpeedKph = 328,
            TorqueNm = 386,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "42.8/57.2",
            WeightKg = 585,
            WheelBaseM = 2.93
        },
        new()
        {
            Class = "Formula HiTech",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula HiTech Gen 1 Model3",
            PowerHp = 662,
            TopSpeedKph = 321,
            TorqueNm = 455,
            Transmission = Transmission6SpeedHPattern,
            WeightDistribution = "43.2/56.8",
            WeightKg = 585,
            WheelBaseM = 2.89
        },
        new()
        {
            Class = "Formula HiTech",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV10,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula HiTech Gen 1 Model4",
            PowerHp = 707,
            TopSpeedKph = 328,
            TorqueNm = 386,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "42.8/57.2",
            WeightKg = 585,
            WheelBaseM = 2.93
        },
        new()
        {
            Class = "Formula HiTech",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "TC",
            Engine = EngineV12,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "McLaren",
            Model = "McLaren Honda MP4/7A",
            PowerHp = 776,
            TopSpeedKph = 338,
            TorqueNm = 419,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "42.2/57.8",
            WeightKg = 610,
            WheelBaseM = 2.98
        },
        new()
        {
            Class = "Formula HiTech",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "ABS,TC",
            Engine = EngineV12,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula HiTech Gen 2 Model1",
            PowerHp = 727,
            TopSpeedKph = 335,
            TorqueNm = 378,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "42.2/57.8",
            WeightKg = 610,
            WheelBaseM = 2.88
        },
        new()
        {
            Class = "Formula HiTech",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "ABS,TC",
            Engine = EngineV10,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula HiTech Gen 2 Model2",
            PowerHp = 707,
            TopSpeedKph = 328,
            TorqueNm = 386,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "42.8/57.2",
            WeightKg = 585,
            WheelBaseM = 2.93
        },
        new()
        {
            Class = "Formula HiTech",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "ABS,TC",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula HiTech Gen 2 Model3",
            PowerHp = 695,
            TopSpeedKph = 321,
            TorqueNm = 410,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "43.2/56.8",
            WeightKg = 585,
            WheelBaseM = 2.89
        },
        new()
        {
            Class = "Formula HiTech",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "ABS,TC",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "McLaren",
            Model = "McLaren Cosworth MP4/8",
            PowerHp = 690,
            TopSpeedKph = 321,
            TorqueNm = 406,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "43.2/56.8",
            WeightKg = 585,
            WheelBaseM = 2.84
        },
        new()
        {
            Class = "F3",
            Differential = "NA",
            DisplacementL = 2.3,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Dallara",
            Model = "Dallara F301",
            PowerHp = 260,
            TopSpeedKph = 270,
            TorqueNm = 291,
            Transmission = Transmission5SpeedSequential,
            WeightDistribution = "44.0/56.0",
            WeightKg = 560,
            WheelBaseM = 2.60
        },
        new()
        {
            Class = "F3",
            Differential = "NA",
            DisplacementL = 2.3,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Dallara",
            Model = "Dallara F309",
            PowerHp = 260,
            TopSpeedKph = 270,
            TorqueNm = 291,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "44.0/56.0",
            WeightKg = 560,
            WheelBaseM = 2.73
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 1.49,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV6,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = true,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Classic Gen1 Model1",
            PowerHp = 1190,
            TopSpeedKph = 390,
            TorqueNm = 780,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "42.4/57.6",
            WeightKg = 620,
            WheelBaseM = 2.88
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 1.49,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = true,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Classic Gen1 Model2",
            PowerHp = 1300,
            TopSpeedKph = 397,
            TorqueNm = 820,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "41.8/58.2",
            WeightKg = 630,
            WheelBaseM = 2.8
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 1.49,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV6,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = true,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Lotus",
            Model = "Lotus Renault 98T",
            PowerHp = 1280,
            TopSpeedKph = 397,
            TorqueNm = 795,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "42.4/57.6",
            WeightKg = 620,
            WheelBaseM = 2.75
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Classic Gen2 Model1",
            PowerHp = 626,
            TopSpeedKph = 317,
            TorqueNm = 626,
            Transmission = Transmission6SpeedHPattern,
            WeightDistribution = "42.4/57.6",
            WeightKg = 610,
            WheelBaseM = 2.88
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Classic Gen2 Model2",
            PowerHp = 662,
            TopSpeedKph = 323,
            TorqueNm = 455,
            Transmission = Transmission6SpeedHPattern,
            WeightDistribution = "42.4/57.6",
            WeightKg = 610,
            WheelBaseM = 2.88
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 1.49,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV6,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = true,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Classic Gen2 Model3",
            PowerHp = 675,
            TopSpeedKph = 325,
            TorqueNm = 430,
            Transmission = Transmission6SpeedHPattern,
            WeightDistribution = "42.6/57.4",
            WeightKg = 620,
            WheelBaseM = 2.88
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 1.49,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV6,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = true,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "McLaren",
            Model = "McLaren Honda MP4/4",
            PowerHp = 675,
            TopSpeedKph = 325,
            TorqueNm = 420,
            Transmission = Transmission6SpeedHPattern,
            WeightDistribution = "42.6/57.4",
            WeightKg = 620,
            WheelBaseM = 2.86
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV12,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Classic Gen3 Model1",
            PowerHp = 725,
            TopSpeedKph = 335,
            TorqueNm = 378,
            Transmission = Transmission6SpeedHPattern,
            WeightDistribution = "42.2/57.8",
            WeightKg = 620,
            WheelBaseM = 2.88
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Classic Gen3 Model2",
            PowerHp = 632,
            TopSpeedKph = 310,
            TorqueNm = 439,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "42.8/57.2",
            WeightKg = 610,
            WheelBaseM = 2.88
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV10,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Classic Gen3 Model3",
            PowerHp = 734,
            TopSpeedKph = 330,
            TorqueNm = 401,
            Transmission = Transmission6SpeedHPattern,
            WeightDistribution = "43.0/57.0",
            WeightKg = 610,
            WheelBaseM = 2.88
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Classic Gen3 Model4",
            PowerHp = 661,
            TopSpeedKph = 320,
            TorqueNm = 456,
            Transmission = Transmission6SpeedHPattern,
            WeightDistribution = "43.2/56.8",
            WeightKg = 585,
            WheelBaseM = 2.88
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV10,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "McLaren",
            Model = "McLaren Honda MP4/5B",
            PowerHp = 690,
            TopSpeedKph = 330,
            TorqueNm = 408,
            Transmission = Transmission6SpeedHPattern,
            WeightDistribution = "42.4/57.6",
            WeightKg = 610,
            WheelBaseM = 2.93
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV12,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Classic Gen4 Model1",
            PowerHp = 727,
            TopSpeedKph = 335,
            TorqueNm = 378,
            Transmission = Transmission7SpeedSequential,
            WeightDistribution = "42.2/57.8",
            WeightKg = 620,
            WheelBaseM = 2.88
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV10,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Classic Gen4 Model2",
            PowerHp = 707,
            TopSpeedKph = 328,
            TorqueNm = 386,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "42.8/57.2",
            WeightKg = 610,
            WheelBaseM = 2.93
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Classic Gen4 Model3",
            PowerHp = 662,
            TopSpeedKph = 321,
            TorqueNm = 455,
            Transmission = Transmission6SpeedHPattern,
            WeightDistribution = "43.2/56.8",
            WeightKg = 585,
            WheelBaseM = 2.89
        },
        new()
        {
            Class = "Formula Classic",
            Differential = "NA",
            DisplacementL = 3.5,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV12,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "McLaren",
            Model = "McLaren Honda MP4/6",
            PowerHp = 757,
            TopSpeedKph = 338,
            TorqueNm = 419,
            Transmission = Transmission6SpeedHPattern,
            WeightDistribution = "42.2/57.8",
            WeightKg = 610,
            WheelBaseM = 2.90
        },
        new()
        {
            Class = "Formula Dirt",
            Differential = "NA",
            DisplacementL = 1.8,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineFlat4,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Dirt",
            PowerHp = 84,
            TopSpeedKph = 141,
            TorqueNm = 144,
            Transmission = Transmission4SpeedHPattern,
            WeightDistribution = "46.0/54.0",
            WeightKg = 725,
            WheelBaseM = 2.51
        },
        new()
        {
            Class = "Formula Inter",
            Differential = "NA",
            DisplacementL = 2,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Lopes",
            Model = "Formula Inter MG-15",
            PowerHp = 161,
            TopSpeedKph = 205,
            TorqueNm = 186,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "42.4/57.6",
            WeightKg = 615,
            WheelBaseM = 2.46
        },
        new()
        {
            Class = "Formula Junior",
            Differential = "NA",
            DisplacementL = 1,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Junior",
            PowerHp = 126,
            TopSpeedKph = 205,
            TorqueNm = 116,
            Transmission = Transmission4SpeedHPattern,
            WeightDistribution = "44.0/56.0",
            WeightKg = 483,
            WheelBaseM = 2.31
        },
        new()
        {
            Class = "Formula Reiza",
            Differential = "NA",
            DisplacementL = 2.4,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = true,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Reiza",
            PowerHp = 754,
            TopSpeedKph = 343,
            TorqueNm = 316,
            Transmission = Transmission7SpeedSequential,
            WeightDistribution = "46.6/53.4",
            WeightKg = 620,
            WheelBaseM = 3.39
        },
        new()
        {
            Class = "Formula Retro",
            Differential = "NA",
            DisplacementL = 3,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Brabham",
            Model = "Brabham BT44",
            PowerHp = 480,
            TopSpeedKph = 295,
            TorqueNm = 358,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "39.4/60.6",
            WeightKg = 650,
            WheelBaseM = 2.47
        },
        new()
        {
            Class = "Formula Retro",
            Differential = "NA",
            DisplacementL = 3,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV12,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Retro V12",
            PowerHp = 516,
            TopSpeedKph = 305,
            TorqueNm = 330,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "38.8/61.2",
            WeightKg = 670,
            WheelBaseM = 2.67
        },
        new()
        {
            Class = "Formula Retro",
            Differential = "NA",
            DisplacementL = 3,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Retro V8",
            PowerHp = 480,
            TopSpeedKph = 294,
            TorqueNm = 358,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "39.2/60.8",
            WeightKg = 655,
            WheelBaseM = 2.67
        },
        new()
        {
            Class = "Formula Retro",
            Differential = "NA",
            DisplacementL = 3,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Lotus",
            Model = "Lotus 72E",
            PowerHp = 480,
            TopSpeedKph = 294,
            TorqueNm = 358,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "39.4/60.6",
            WeightKg = 640,
            WheelBaseM = 2.54
        },
        new()
        {
            Class = "Formula Retro",
            Differential = "NA",
            DisplacementL = 3,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "McLaren",
            Model = "McLaren M23",
            PowerHp = 480,
            TopSpeedKph = 290,
            TorqueNm = 358,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "39.0/61.0",
            WeightKg = 655,
            WheelBaseM = 2.56
        },
        new()
        {
            Class = "Formula Retro",
            Differential = "NA",
            DisplacementL = 3,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineFlat12,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Brabham",
            Model = "Brabham Alfa Romeo BT46B",
            PowerHp = 510,
            TopSpeedKph = 295,
            TorqueNm = 419,
            Transmission = Transmission6SpeedHPattern,
            WeightDistribution = "39.0/61.0",
            WeightKg = 670,
            WheelBaseM = 2.58
        },
        new()
        {
            Class = "Formula Retro",
            Differential = "NA",
            DisplacementL = 3,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV12,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Brabham",
            Model = "Brabham Cosworth BT49",
            PowerHp = 502,
            TopSpeedKph = 319,
            TorqueNm = 373,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "39.2/60.8",
            WeightKg = 665,
            WheelBaseM = 2.72
        },
        new()
        {
            Class = "Formula Retro",
            Differential = "NA",
            DisplacementL = 3,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Retro Gen2",
            PowerHp = 501,
            TopSpeedKph = 300,
            TorqueNm = 373,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "39.3/60.8",
            WeightKg = 655,
            WheelBaseM = 2.65
        },
        new()
        {
            Class = "Formula Retro",
            Differential = "NA",
            DisplacementL = 3,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Lotus",
            Model = "Lotus 79",
            PowerHp = 501,
            TopSpeedKph = 300,
            TorqueNm = 373,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "39.2/60.8",
            WeightKg = 655,
            WheelBaseM = 2.78
        },
        new()
        {
            Class = "Formula Retro",
            Differential = "NA",
            DisplacementL = 1.5,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Brabham",
            Model = "Brabham BMW BT52",
            PowerHp = 910,
            TopSpeedKph = 345,
            TorqueNm = 780,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "32.6/67.4",
            WeightKg = 625,
            WheelBaseM = 2.85
        },
        new()
        {
            Class = "Formula Retro",
            Differential = "NA",
            DisplacementL = 3,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Retro Gen3 DFY",
            PowerHp = 526,
            TopSpeedKph = 296,
            TorqueNm = 392,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "40.0/60.0",
            WeightKg = 640,
            WheelBaseM = 2.69
        },
        new()
        {
            Class = "Formula Retro",
            Differential = "NA",
            DisplacementL = 1.5,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV6,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Retro Gen3 Turbo",
            PowerHp = 830,
            TopSpeedKph = 355,
            TorqueNm = 565,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "40.0/60.0",
            WeightKg = 650,
            WheelBaseM = 2.69
        },
        new()
        {
            Class = "Formula Retro",
            Differential = "NA",
            DisplacementL = 3,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "McLaren",
            Model = "McLaren Cosworth MP4/1C",
            PowerHp = 526,
            TopSpeedKph = 307,
            TorqueNm = 392,
            Transmission = Transmission5SpeedHPattern,
            WeightDistribution = "41.8/58.2",
            WeightKg = 625,
            WheelBaseM = 2.68
        },
        new()
        {
            Class = "Formula Trainer",
            Differential = "NA",
            DisplacementL = 1.6,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Trainer",
            PowerHp = 113,
            TopSpeedKph = 225,
            TorqueNm = 158,
            Transmission = Transmission4SpeedHPattern,
            WeightDistribution = "45.0/55.0",
            WeightKg = 495,
            WheelBaseM = 2.53
        },
        new()
        {
            Class = "Formula Trainer",
            Differential = "NA",
            DisplacementL = 1.6,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineStraight4,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = false,
            HasBoostButton = false,
            HasDrs = false,
            HasHeadlights = false,
            HasOnBoardBrakeBias = false,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Trainer Advanced",
            PowerHp = 155,
            TopSpeedKph = 250,
            TorqueNm = 180,
            Transmission = Transmission4SpeedSequential,
            WeightDistribution = "45.0/55.0",
            WeightKg = 495,
            WheelBaseM = 2.53
        },
        new()
        {
            Class = "Formula Ultimate",
            Differential = "NA",
            DisplacementL = 1.6,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV6,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Ultimate Gen1",
            PowerHp = 960,
            TopSpeedKph = 349,
            TorqueNm = 640,
            Transmission = Transmission8SpeedSequential,
            WeightDistribution = "46.2/53.8",
            WeightKg = 734,
            WheelBaseM = 3.49
        },
        new()
        {
            Class = "Formula Ultimate",
            Differential = "NA",
            DisplacementL = 1.6,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV6,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = false,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reiza",
            Model = "Formula Ultimate Gen2",
            PowerHp = 965,
            TopSpeedKph = 346,
            TorqueNm = 640,
            Transmission = Transmission8SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 798,
            WheelBaseM = 3.6
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Lola",
            Model = "Lola T95/00 Ford Cosworth",
            PowerHp = 810,
            TopSpeedKph = 325,
            TorqueNm = 424,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Lola",
            Model = "Lola T95/00 Mercedes-Benz",
            PowerHp = 810,
            TopSpeedKph = 325,
            TorqueNm = 424,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reynard",
            Model = "Reynard 95i Ford Cosworth",
            PowerHp = 810,
            TopSpeedKph = 325,
            TorqueNm = 424,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reynard",
            Model = "Reynard 95i Honda",
            PowerHp = 810,
            TopSpeedKph = 325,
            TorqueNm = 424,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reynard",
            Model = "Reynard 95i Mercedes-Benz",
            PowerHp = 810,
            TopSpeedKph = 325,
            TorqueNm = 424,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Lola",
            Model = "Lola T98/00 Ford Cosworth",
            PowerHp = 875,
            TopSpeedKph = 335,
            TorqueNm = 448,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reynard",
            Model = "Reynard 98i Ford Cosworth",
            PowerHp = 875,
            TopSpeedKph = 335,
            TorqueNm = 448,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reynard",
            Model = "Reynard 98i Honda",
            PowerHp = 875,
            TopSpeedKph = 335,
            TorqueNm = 448,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reynard",
            Model = "Reynard 98i Mercedes-Benz",
            PowerHp = 875,
            TopSpeedKph = 335,
            TorqueNm = 448,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reynard",
            Model = "Reynard 98i Toyota",
            PowerHp = 875,
            TopSpeedKph = 335,
            TorqueNm = 430,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Swift",
            Model = "Swift 009c Ford-Cosworth",
            PowerHp = 875,
            TopSpeedKph = 335,
            TorqueNm = 448,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Lola",
            Model = "Lola B2K00 Ford-Cosworth",
            PowerHp = 910,
            TopSpeedKph = 340,
            TorqueNm = 465,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Lola",
            Model = "Lola B2K00 Mercedes-Benz",
            PowerHp = 895,
            TopSpeedKph = 340,
            TorqueNm = 455,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Lola",
            Model = "Lola B2K00 Toyota",
            PowerHp = 917,
            TopSpeedKph = 340,
            TorqueNm = 465,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reynard",
            Model = "Reynard 2Ki Ford-Cosworth",
            PowerHp = 910,
            TopSpeedKph = 340,
            TorqueNm = 465,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reynard",
            Model = "Reynard 2Ki Honda",
            PowerHp = 917,
            TopSpeedKph = 340,
            TorqueNm = 465,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reynard",
            Model = "Reynard 2Ki Mercedes-Benz",
            PowerHp = 895,
            TopSpeedKph = 340,
            TorqueNm = 455,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        },
        new()
        {
            Class = "Formula USA",
            Differential = "NA",
            DisplacementL = 2.65,
            Driveline = DrivelineRwd,
            Electronics = "None",
            Engine = EngineV8,
            EnginePlacement = EnginePlacementMidRear,
            HasAdjustableTurbo = true,
            HasBoostButton = false,
            HasDrs = true,
            HasHeadlights = false,
            HasOnBoardBrakeBias = true,
            HasOnBoardRollBars = true,
            HasPitSpeedLimiter = true,
            Manufacturer = "Reynard",
            Model = "Reynard 2Ki Toyota",
            PowerHp = 917,
            TopSpeedKph = 340,
            TorqueNm = 465,
            Transmission = Transmission6SpeedSequential,
            WeightDistribution = "46.0/54.0",
            WeightKg = 770,
            WheelBaseM = 3.14
        }
    ];

    public static Ams2CarInfoProvider Instance => singletonInstance ??= new Ams2CarInfoProvider();

    public Ams2CarInfo? FindByModel(string model)
    {
        return this.cars.FirstOrDefault(c => c.Model == model);
    }

    public ReadOnlyCollection<Ams2CarInfo> GetCarInfos()
    {
        return this.cars.AsReadOnly();
    }
}