using SimRacingSdk.Ace.Core.Abstractions;
using SimRacingSdk.Ace.Core.Models;

namespace SimRacingSdk.Ace.Core;

// Sourced from Mike's own manually-gathered ace-cars.csv (repo root, populated 2026-07-28 from
// Evo's in-game car list). ModelId is the preset id string from the ACE Dedicated Server's
// cars.json (found 2026-08-12 at "<Steam>\steamapps\common\Assetto Corsa EVO Dedicated
// Server\cars.json"), matched to each row here by pairing cars.json's display_name (which
// splits into a base name plus a " - " variant suffix) against this list's Manufacturer/Name/
// Variant and cross-checking performance_indicator against PerformanceRating - display names
// and variant wording differ between the two sources (e.g. "Alfa Romeo" vs Mike's "Alpha
// Romeo", "Huracán" vs "Huracan"), but every base-name group matched 1:1 in count and order.
public class AceCarInfoProvider : IAceCarInfoProvider
{
    private static AceCarInfoProvider? singletonInstance;

    private readonly List<AceCarInfo> cars =
    [
        new() { ModelId = "preset_695b_mech_1", Manufacturer = "Abarth", Name = "695 Biposto", Variant = "", PerformanceRating = 10.2, Categories = "Road:Modern:ICE", DriveLayout = "FWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Hatch Back", RacingClass = "", Year = 2015, PowerPs = 190, TorqueNm = 250, DisplacementL = 1.4, Cylinders = 4, WeightKg = 997, MaxSpeedKmh = 230, ZeroToOneHundredKmh = 5.9, Gears = 5, FuelTankL = 35, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_75t_mech_1", Manufacturer = "Alpha Romeo", Name = "75 Turbo Evoluzione", Variant = "", PerformanceRating = 8, Categories = "Road:Vintage:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Saloon", RacingClass = "", Year = 1987, PowerPs = 155, TorqueNm = 226, DisplacementL = 1.8, Cylinders = 4, WeightKg = 1150, MaxSpeedKmh = 225, ZeroToOneHundredKmh = 7.6, Gears = 5, FuelTankL = 49, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_gtam_mech_1", Manufacturer = "Alpha Romeo", Name = "Giulia GT Am", Variant = "", PerformanceRating = 12.8, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "", Year = 2021, PowerPs = 540, TorqueNm = 600, DisplacementL = 2.5, Cylinders = 6, WeightKg = 1580, MaxSpeedKmh = 300, ZeroToOneHundredKmh = 3.4, Gears = 8, FuelTankL = 58, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_sprintgta_mech_1", Manufacturer = "Alpha Romeo", Name = "Giulia Sprint GTA", Variant = "", PerformanceRating = 7.7, Categories = "Road:Vintage:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "Rally", Year = 1965, PowerPs = 170, TorqueNm = 180, DisplacementL = 1.5, Cylinders = 4, WeightKg = 760, MaxSpeedKmh = 220, ZeroToOneHundredKmh = 8, Gears = 5, FuelTankL = 58, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_mln_mech_1", Manufacturer = "Alpha Romeo", Name = "Elettrico 280 CV Veloce", Variant = "", PerformanceRating = 10.5, Categories = "Road:Modern:EV", DriveLayout = "FWD", EngineLayout = "Front", Engine = "Electric Motor", Body = "SUV", RacingClass = "", Year = 2024, PowerPs = 207, TorqueNm = 345, DisplacementL = null, Cylinders = null, WeightKg = 1560, MaxSpeedKmh = 200, ZeroToOneHundredKmh = 5.9, Gears = null, FuelTankL = null, BatteryKwh = 54, MaxRpm = null },
        new() { ModelId = "preset_a110s_mech_1", Manufacturer = "Alpine", Name = "A110 3 Aero Kit", Variant = "", PerformanceRating = 12, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "", Year = 2021, PowerPs = 300, TorqueNm = 340, DisplacementL = 1.8, Cylinders = 4, WeightKg = 1110, MaxSpeedKmh = 275, ZeroToOneHundredKmh = 4.1, Gears = 7, FuelTankL = 45, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_a290b_mech_1", Manufacturer = "Alpine", Name = "A290 Beta", Variant = "", PerformanceRating = 9.8, Categories = "Road:Modern:EV", DriveLayout = "AWD", EngineLayout = "Mid", Engine = "Electric Motor", Body = "Hatch Back", RacingClass = "", Year = 2023, PowerPs = 220, TorqueNm = 300, DisplacementL = null, Cylinders = null, WeightKg = 1479, MaxSpeedKmh = 170, ZeroToOneHundredKmh = 6.4, Gears = null, FuelTankL = null, BatteryKwh = 52, MaxRpm = null },
        new() { ModelId = "preset_r8gt3_mech_1", Manufacturer = "Audi", Name = "R8 LMS GT3 Evo II", Variant = "", PerformanceRating = 20.5, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "GT3", Year = 2022, PowerPs = 550, TorqueNm = 600, DisplacementL = 5.2, Cylinders = 10, WeightKg = 1400, MaxSpeedKmh = 300, ZeroToOneHundredKmh = 3, Gears = 6, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_r8gt4_mech_1", Manufacturer = "Audi", Name = "R8 LMS GT4 Evo", Variant = "", PerformanceRating = 15.5, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "GT4", Year = 2022, PowerPs = 495, TorqueNm = 550, DisplacementL = 5.2, Cylinders = 10, WeightKg = 1460, MaxSpeedKmh = 280, ZeroToOneHundredKmh = 3.5, Gears = 6, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_rs3_mech_1", Manufacturer = "Audi", Name = "RS 3 Sportback", Variant = "", PerformanceRating = 12.2, Categories = "Road:Modern:ICE", DriveLayout = "AWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Hatch Back", RacingClass = "", Year = 2022, PowerPs = 400, TorqueNm = 500, DisplacementL = 2.5, Cylinders = 5, WeightKg = 1570, MaxSpeedKmh = 250, ZeroToOneHundredKmh = 3.8, Gears = 7, FuelTankL = 55, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_rs6_mech_1", Manufacturer = "Audi", Name = "RS 6 Avant", Variant = "", PerformanceRating = 12.2, Categories = "Road:Modern:ICE", DriveLayout = "AWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Estate", RacingClass = "", Year = 2022, PowerPs = 600, TorqueNm = 800, DisplacementL = 4, Cylinders = 8, WeightKg = 2075, MaxSpeedKmh = 250, ZeroToOneHundredKmh = 3.6, Gears = 8, FuelTankL = 73, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_sq_mech_1", Manufacturer = "Audi", Name = "Sport Quattro", Variant = "", PerformanceRating = 10.7, Categories = "Road:Vintage:ICE", DriveLayout = "AWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "", Year = 1983, PowerPs = 306, TorqueNm = 350, DisplacementL = 2.1, Cylinders = 5, WeightKg = 1300, MaxSpeedKmh = 250, ZeroToOneHundredKmh = 4.9, Gears = 5, FuelTankL = 90, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_m2csr_mech_1", Manufacturer = "BMW", Name = "M2 CS Racing", Variant = "No Power Stick", PerformanceRating = 13.1, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "Cup:TCX", Year = 2020, PowerPs = 365, TorqueNm = 550, DisplacementL = 3, Cylinders = 6, WeightKg = 1610, MaxSpeedKmh = 270, ZeroToOneHundredKmh = 4.2, Gears = 7, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_m2csr_mech_2", Manufacturer = "BMW", Name = "M2 CS Racing", Variant = "Black Power Stick", PerformanceRating = 13.5, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "Cup:TCX", Year = 2020, PowerPs = 450, TorqueNm = 550, DisplacementL = 3, Cylinders = 6, WeightKg = 1610, MaxSpeedKmh = 295, ZeroToOneHundredKmh = 3.8, Gears = 7, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_m2_mech_1", Manufacturer = "BMW", Name = "M2 Coupe", Variant = "M2 G87 Coupe", PerformanceRating = 11.5, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "", Year = 2021, PowerPs = 460, TorqueNm = 550, DisplacementL = 3, Cylinders = 6, WeightKg = 1775, MaxSpeedKmh = 302, ZeroToOneHundredKmh = 3.8, Gears = 6, FuelTankL = 52, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_m2_mech_2", Manufacturer = "BMW", Name = "M2 Coupe", Variant = "M2 G87 Coupe M Performance", PerformanceRating = 11.7, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "", Year = 2021, PowerPs = 460, TorqueNm = 550, DisplacementL = 3, Cylinders = 6, WeightKg = 1775, MaxSpeedKmh = 302, ZeroToOneHundredKmh = 3.8, Gears = 6, FuelTankL = 52, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_m3evoiii_mech_1", Manufacturer = "BMW", Name = "M3 E30 Sporte Evo", Variant = "", PerformanceRating = 9.4, Categories = "Road:Youngtimer:ICE", DriveLayout = "", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 1990, PowerPs = 238, TorqueNm = 240, DisplacementL = 2.5, Cylinders = 6, WeightKg = 1200, MaxSpeedKmh = 248, ZeroToOneHundredKmh = 6.5, Gears = 5, FuelTankL = 70, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_e46csl_mech_1", Manufacturer = "BMW", Name = "M3 E45 CSL", Variant = "", PerformanceRating = 10, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 2003, PowerPs = 350, TorqueNm = 370, DisplacementL = 3.2, Cylinders = 6, WeightKg = 1450, MaxSpeedKmh = 250, ZeroToOneHundredKmh = 4.9, Gears = 8, FuelTankL = 63, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_m4csl_mech_1", Manufacturer = "BMW", Name = "M4 CSL", Variant = "", PerformanceRating = 11.9, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "", Year = 2021, PowerPs = 550, TorqueNm = 650, DisplacementL = 3, Cylinders = 6, WeightKg = 1625, MaxSpeedKmh = 250, ZeroToOneHundredKmh = 3.7, Gears = 8, FuelTankL = 59, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_m4gt3_mech_1", Manufacturer = "BMW", Name = "M4 GT3 Evo", Variant = "", PerformanceRating = 21.1, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "GT3", Year = 2025, PowerPs = 590, TorqueNm = 700, DisplacementL = 3, Cylinders = 6, WeightKg = 1400, MaxSpeedKmh = 300, ZeroToOneHundredKmh = 2.9, Gears = 6, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_m8c_mech_1", Manufacturer = "BMW", Name = "M8 Competition", Variant = "", PerformanceRating = 11.6, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "", Year = 2021, PowerPs = 625, TorqueNm = 750, DisplacementL = 4.4, Cylinders = 8, WeightKg = 1885, MaxSpeedKmh = 250, ZeroToOneHundredKmh = 3.2, Gears = 8, FuelTankL = 68, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "ks_caterham_485_csr_mech_1", Manufacturer = "Caterham", Name = "485 CSR", Variant = "485 CSR Road", PerformanceRating = 7.8, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Cabriolet", RacingClass = "", Year = 2023, PowerPs = 237, TorqueNm = 206, DisplacementL = 2, Cylinders = 4, WeightKg = 630, MaxSpeedKmh = 225, ZeroToOneHundredKmh = 3.9, Gears = 5, FuelTankL = 36, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "ks_caterham_485_csr_mech_2", Manufacturer = "Caterham", Name = "485 CSR", Variant = "485 CSR Track", PerformanceRating = 7.8, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Cabriolet", RacingClass = "", Year = 2023, PowerPs = 237, TorqueNm = 206, DisplacementL = 2, Cylinders = 4, WeightKg = 630, MaxSpeedKmh = 225, ZeroToOneHundredKmh = 3.9, Gears = 5, FuelTankL = 36, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "ks_caterham_485_csr_mech_3", Manufacturer = "Caterham", Name = "485 CSR", Variant = "485 CSR Final Edition", PerformanceRating = 7.8, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Cabriolet", RacingClass = "", Year = 2023, PowerPs = 237, TorqueNm = 206, DisplacementL = 2, Cylinders = 4, WeightKg = 630, MaxSpeedKmh = 225, ZeroToOneHundredKmh = 3.9, Gears = 5, FuelTankL = 36, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "ks_caterham_acmd_mech_1", Manufacturer = "Caterham", Name = "Academy", Variant = "", PerformanceRating = 8.8, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Cabriolet", RacingClass = "", Year = 2023, PowerPs = 135, TorqueNm = 150, DisplacementL = 1.5, Cylinders = 4, WeightKg = 630, MaxSpeedKmh = 200, ZeroToOneHundredKmh = 6, Gears = 5, FuelTankL = 36, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_zl1_mech_1", Manufacturer = "Chevrolet", Name = "Camaro ZL1", Variant = "Zl1", PerformanceRating = 12.3, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Supercharged", Body = "Coupe", RacingClass = "", Year = 2023, PowerPs = 659, TorqueNm = 881, DisplacementL = 6.2, Cylinders = 8, WeightKg = 1753, MaxSpeedKmh = 318, ZeroToOneHundredKmh = 3.5, Gears = 6, FuelTankL = 72, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_zl1_mech_2", Manufacturer = "Chevrolet", Name = "Camaro ZL1", Variant = "Zl1 1LE Extreme Track Performance", PerformanceRating = 12.5, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Supercharged", Body = "Coupe", RacingClass = "", Year = 2023, PowerPs = 659, TorqueNm = 881, DisplacementL = 6.2, Cylinders = 8, WeightKg = 1753, MaxSpeedKmh = 318, ZeroToOneHundredKmh = 3.5, Gears = 6, FuelTankL = 72, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_dalexp_mech_1", Manufacturer = "Dallara", Name = "EXP", Variant = "", PerformanceRating = 22.5, Categories = "Track:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Cabriolet", RacingClass = "", Year = 2023, PowerPs = 500, TorqueNm = 700, DisplacementL = 2.3, Cylinders = 4, WeightKg = 890, MaxSpeedKmh = 290, ZeroToOneHundredKmh = 3, Gears = 6, FuelTankL = 55, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_dalsc_mech_1", Manufacturer = "Dallara", Name = "Stradale", Variant = "Stradale Targa/Coupe", PerformanceRating = 19, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Cabriolet", RacingClass = "", Year = 2017, PowerPs = 400, TorqueNm = 500, DisplacementL = 2.3, Cylinders = 4, WeightKg = 855, MaxSpeedKmh = 280, ZeroToOneHundredKmh = 3.3, Gears = 6, FuelTankL = 55, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_dalsc_mech_2", Manufacturer = "Dallara", Name = "Stradale", Variant = "Stradale Barchetta/Spider", PerformanceRating = 19, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Cabriolet", RacingClass = "", Year = 2017, PowerPs = 400, TorqueNm = 500, DisplacementL = 2.3, Cylinders = 4, WeightKg = 855, MaxSpeedKmh = 280, ZeroToOneHundredKmh = 3.3, Gears = 6, FuelTankL = 55, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_dalsc_mech_3", Manufacturer = "Dallara", Name = "Stradale", Variant = "Trackday", PerformanceRating = 21.3, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Cabriolet", RacingClass = "", Year = 2017, PowerPs = 400, TorqueNm = 500, DisplacementL = 2.3, Cylinders = 4, WeightKg = 855, MaxSpeedKmh = 280, ZeroToOneHundredKmh = 3.3, Gears = 6, FuelTankL = 55, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_288gto_mech_1", Manufacturer = "Ferrari", Name = "288 GTO", Variant = "", PerformanceRating = 11.1, Categories = "Road:Vintage:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "", Year = 1984, PowerPs = 400, TorqueNm = 496, DisplacementL = 2.9, Cylinders = 8, WeightKg = 1160, MaxSpeedKmh = 305, ZeroToOneHundredKmh = 4.7, Gears = 5, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_296gt3_mech_1", Manufacturer = "Ferrari", Name = "295 GT3", Variant = "", PerformanceRating = 22.3, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "GT3", Year = 2022, PowerPs = 550, TorqueNm = 640, DisplacementL = 2.9, Cylinders = 6, WeightKg = 1400, MaxSpeedKmh = 320, ZeroToOneHundredKmh = 2.9, Gears = 6, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_296gtb_mech_1", Manufacturer = "Ferrari", Name = "296 GTB", Variant = "296 GTB", PerformanceRating = 14.7, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "", Year = 2022, PowerPs = 830, TorqueNm = 740, DisplacementL = 3, Cylinders = 6, WeightKg = 1675, MaxSpeedKmh = 330, ZeroToOneHundredKmh = 2.9, Gears = 8, FuelTankL = 65, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_296gtb_mech_2", Manufacturer = "Ferrari", Name = "296 GTB", Variant = "296 GTB Assetto Fiorano", PerformanceRating = 14.7, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "", Year = 2022, PowerPs = 830, TorqueNm = 740, DisplacementL = 3, Cylinders = 6, WeightKg = 1660, MaxSpeedKmh = 330, ZeroToOneHundredKmh = 2.9, Gears = 8, FuelTankL = 65, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_f488ce_mech_1", Manufacturer = "Ferrari", Name = "Trofeo Challenge", Variant = "", PerformanceRating = 20.2, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "GT2:Cup", Year = 2021, PowerPs = 670, TorqueNm = 760, DisplacementL = 3.9, Cylinders = 8, WeightKg = 1410, MaxSpeedKmh = 320, ZeroToOneHundredKmh = 2.9, Gears = 7, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_sp3_mech_1", Manufacturer = "Ferrari", Name = "Daytona SP3", Variant = "", PerformanceRating = 16.1, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Naturally Aspirated", Body = "Convertible", RacingClass = "", Year = 2021, PowerPs = 840, TorqueNm = 697, DisplacementL = 6.5, Cylinders = 12, WeightKg = 1405, MaxSpeedKmh = 340, ZeroToOneHundredKmh = 2.7, Gears = 7, FuelTankL = 86, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_f2004_mech_1", Manufacturer = "Ferrari", Name = "Scuderia Ferrari F2004", Variant = "", PerformanceRating = 41.4, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Naturally Aspirated", Body = "Open Wheel", RacingClass = "Formula", Year = 2004, PowerPs = 900, TorqueNm = 350, DisplacementL = 3, Cylinders = 10, WeightKg = 605, MaxSpeedKmh = 350, ZeroToOneHundredKmh = 2, Gears = 7, FuelTankL = 150, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_f40lm_mech_1", Manufacturer = "Ferrari", Name = "F40 LM", Variant = "", PerformanceRating = 20.2, Categories = "Racing:Youngtimer:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "Prototype", Year = 1993, PowerPs = 900, TorqueNm = 750, DisplacementL = 2.9, Cylinders = 8, WeightKg = 1140, MaxSpeedKmh = 370, ZeroToOneHundredKmh = 3, Gears = 5, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_sf25_mech_1", Manufacturer = "Ferrari", Name = "SF-25", Variant = "", PerformanceRating = 43, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Open Wheel", RacingClass = "Formula", Year = 2025, PowerPs = 1000, TorqueNm = 750, DisplacementL = 1.6, Cylinders = 6, WeightKg = 800, MaxSpeedKmh = 350, ZeroToOneHundredKmh = 2, Gears = 8, FuelTankL = 145, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_escortrs_mech_1", Manufacturer = "Ford", Name = "Escort RS Cosworth", Variant = "", PerformanceRating = 8.4, Categories = "Road:Youngtimer:ICE", DriveLayout = "AWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "", Year = 1994, PowerPs = 227, TorqueNm = 294, DisplacementL = 2, Cylinders = 4, WeightKg = 1275, MaxSpeedKmh = 230, ZeroToOneHundredKmh = 6.1, Gears = 5, FuelTankL = 55, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_msggt3_mech_1", Manufacturer = "Ford", Name = "Mustang GT3", Variant = "", PerformanceRating = 19.4, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "GT3", Year = 2024, PowerPs = 550, TorqueNm = 620, DisplacementL = 5.4, Cylinders = 8, WeightKg = 1400, MaxSpeedKmh = 300, ZeroToOneHundredKmh = 2.8, Gears = 6, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_nsxr_mech_1", Manufacturer = "Honda", Name = "NSX-R 92R", Variant = "", PerformanceRating = 10.8, Categories = "Road:Youngtimer:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 1995, PowerPs = 270, TorqueNm = 285, DisplacementL = 3, Cylinders = 6, WeightKg = 1230, MaxSpeedKmh = 260, ZeroToOneHundredKmh = 4.8, Gears = 5, FuelTankL = 70, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_s2000ap1_mech_1", Manufacturer = "Honda", Name = "S2000 AP 1", Variant = "", PerformanceRating = 9.9, Categories = "Road:Youngtimer:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Cabriolet", RacingClass = "", Year = 2003, PowerPs = 240, TorqueNm = 208, DisplacementL = 2, Cylinders = 4, WeightKg = 1270, MaxSpeedKmh = 240, ZeroToOneHundredKmh = 6.2, Gears = 6, FuelTankL = 50, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_i30n_hb_mech_1", Manufacturer = "Hyundai", Name = "i30 N Hatchback", Variant = "Performance", PerformanceRating = 9.4, Categories = "Road:Modern:ICE", DriveLayout = "FWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Hatch Back", RacingClass = "", Year = 2021, PowerPs = 280, TorqueNm = 392, DisplacementL = 3, Cylinders = 4, WeightKg = 1490, MaxSpeedKmh = 250, ZeroToOneHundredKmh = 5.5, Gears = 6, FuelTankL = 50, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_i30n_hb_mech_2", Manufacturer = "Hyundai", Name = "i30 N Hatchback", Variant = "Drive-N Limited Edition", PerformanceRating = 9.6, Categories = "Road:Modern:ICE", DriveLayout = "FWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Hatch Back", RacingClass = "", Year = 2021, PowerPs = 280, TorqueNm = 392, DisplacementL = 3, Cylinders = 4, WeightKg = 1490, MaxSpeedKmh = 250, ZeroToOneHundredKmh = 5.5, Gears = 6, FuelTankL = 50, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_xbgt2_mech_1", Manufacturer = "KTM", Name = "X-Bow GT2", Variant = "", PerformanceRating = 19.3, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "GT2", Year = 2021, PowerPs = 600, TorqueNm = 615, DisplacementL = 2.5, Cylinders = 5, WeightKg = 1267, MaxSpeedKmh = 300, ZeroToOneHundredKmh = 2.9, Gears = 6, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_xbgt4_mech_1", Manufacturer = "KTM", Name = "X-Bow GT4", Variant = "", PerformanceRating = 19, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "GT4", Year = 2018, PowerPs = 360, TorqueNm = 450, DisplacementL = 2, Cylinders = 4, WeightKg = 975, MaxSpeedKmh = 265, ZeroToOneHundredKmh = 3.9, Gears = 6, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_cntqv_mech_1", Manufacturer = "Lamborghini", Name = "Countach LP5000 Q3", Variant = "", PerformanceRating = 9.5, Categories = "Road:Vintage:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 1988, PowerPs = 455, TorqueNm = 500, DisplacementL = 5.2, Cylinders = 12, WeightKg = 1490, MaxSpeedKmh = 293, ZeroToOneHundredKmh = 5.2, Gears = 5, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_stevo2_mech_1", Manufacturer = "Lamborghini", Name = "Huracan ST EVO2", Variant = "", PerformanceRating = 18.4, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "GT2:Cup", Year = 2021, PowerPs = 620, TorqueNm = 570, DisplacementL = 5.2, Cylinders = 10, WeightKg = 1250, MaxSpeedKmh = 310, ZeroToOneHundredKmh = 2.8, Gears = 6, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_sto_mech_1", Manufacturer = "Lamborghini", Name = "Huracan STO", Variant = "STO", PerformanceRating = 15.1, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 2021, PowerPs = 640, TorqueNm = 565, DisplacementL = 5.2, Cylinders = 10, WeightKg = 1519, MaxSpeedKmh = 310, ZeroToOneHundredKmh = 3, Gears = 7, FuelTankL = 80, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_sto_mech_2", Manufacturer = "Lamborghini", Name = "Huracan STO", Variant = "STO Track Options", PerformanceRating = 15.1, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 2021, PowerPs = 640, TorqueNm = 565, DisplacementL = 5.2, Cylinders = 10, WeightKg = 1519, MaxSpeedKmh = 310, ZeroToOneHundredKmh = 3, Gears = 7, FuelTankL = 80, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_mcgt2_mech_1", Manufacturer = "Maserati", Name = "GT2", Variant = "", PerformanceRating = 17.7, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "GT2", Year = 2023, PowerPs = 630, TorqueNm = 700, DisplacementL = 3, Cylinders = 6, WeightKg = 1400, MaxSpeedKmh = 300, ZeroToOneHundredKmh = 2.8, Gears = 6, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_mx5na_mech_1", Manufacturer = "Mazda", Name = "MX-5 NA", Variant = "MX-5 NA Facelift", PerformanceRating = 9.1, Categories = "Road:Youngtimer:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Cabriolet", RacingClass = "", Year = 1990, PowerPs = 115, TorqueNm = 135, DisplacementL = 1.6, Cylinders = 4, WeightKg = 950, MaxSpeedKmh = 195, ZeroToOneHundredKmh = 8.8, Gears = 5, FuelTankL = 45, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_mx5na_mech_2", Manufacturer = "Mazda", Name = "MX-5 NA", Variant = "MX-5 NA Eunos R8 Limited", PerformanceRating = 9.3, Categories = "Road:Youngtimer:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Cabriolet", RacingClass = "", Year = 1990, PowerPs = 131, TorqueNm = 152, DisplacementL = 1.6, Cylinders = 4, WeightKg = 950, MaxSpeedKmh = 195, ZeroToOneHundredKmh = 8.8, Gears = 5, FuelTankL = 45, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_mx5ndcup_mech_1", Manufacturer = "Mazda", Name = "MX5 ND Cup", Variant = "MX-5 ND Global Cup - ND1 Manual", PerformanceRating = 10.9, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Cabriolet", RacingClass = "Cup", Year = 2016, PowerPs = 155, TorqueNm = 200, DisplacementL = 2, Cylinders = 4, WeightKg = 1020, MaxSpeedKmh = 225, ZeroToOneHundredKmh = 6.5, Gears = 6, FuelTankL = 45, BatteryKwh = null, MaxRpm = 7000 },
        new() { ModelId = "preset_mx5ndcup_mech_2", Manufacturer = "Mazda", Name = "MX5 ND Cup", Variant = "MX-5 ND Global Cup - ND1 Sequential", PerformanceRating = 11.2, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Cabriolet", RacingClass = "Cup", Year = 2016, PowerPs = 181, TorqueNm = 200, DisplacementL = 2, Cylinders = 4, WeightKg = 1020, MaxSpeedKmh = 240, ZeroToOneHundredKmh = 6, Gears = 6, FuelTankL = 45, BatteryKwh = null, MaxRpm = 7500 },
        new() { ModelId = "preset_amggt2_mech_1", Manufacturer = "Mercedes", Name = "AMG GT2", Variant = "", PerformanceRating = 18, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "GT2", Year = 2023, PowerPs = 707, TorqueNm = 800, DisplacementL = 4, Cylinders = 8, WeightKg = 1400, MaxSpeedKmh = 300, ZeroToOneHundredKmh = 2.8, Gears = 6, FuelTankL = 120, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_190e_mech_1", Manufacturer = "Mercedes", Name = "190E Evo II", Variant = "", PerformanceRating = 9.8, Categories = "Road:Youngtimer:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Sedan", RacingClass = "", Year = 1996, PowerPs = 235, TorqueNm = 245, DisplacementL = 2.5, Cylinders = 4, WeightKg = 1340, MaxSpeedKmh = 250, ZeroToOneHundredKmh = 7.1, Gears = 5, FuelTankL = 70, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_jcs_mech_1", Manufacturer = "Mini", Name = "John Cooper S", Variant = "MK VI John Cooper S", PerformanceRating = 9.5, Categories = "Road:Youngtimer:ICE", DriveLayout = "FWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Sedan", RacingClass = "", Year = 1990, PowerPs = 83, TorqueNm = 114, DisplacementL = 1.3, Cylinders = 4, WeightKg = 710, MaxSpeedKmh = 163, ZeroToOneHundredKmh = 9.8, Gears = 4, FuelTankL = 34, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_jcs_mech_2", Manufacturer = "Mini", Name = "John Cooper S", Variant = "MK VI B16 Tune", PerformanceRating = 10.8, Categories = "Road:Youngtimer:ICE", DriveLayout = "FWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Sedan", RacingClass = "", Year = 1990, PowerPs = 160, TorqueNm = 150, DisplacementL = 1.6, Cylinders = 4, WeightKg = 710, MaxSpeedKmh = 200, ZeroToOneHundredKmh = 6, Gears = 5, FuelTankL = 34, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_240z_mech_1", Manufacturer = "Nissan", Name = "Datsun 240 Z", Variant = "240Z (S30)", PerformanceRating = 7.3, Categories = "Road:Vintage:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 1971, PowerPs = 153, TorqueNm = 198, DisplacementL = 2.4, Cylinders = 6, WeightKg = 1115, MaxSpeedKmh = 201, ZeroToOneHundredKmh = 8, Gears = 4, FuelTankL = 60, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_240z_mech_2", Manufacturer = "Nissan", Name = "Datsun 240 Z", Variant = "240Z (S30) 0-Nose Tune", PerformanceRating = 8.1, Categories = "Road:Vintage:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 1971, PowerPs = 197, TorqueNm = 240, DisplacementL = 2.8, Cylinders = 6, WeightKg = 1140, MaxSpeedKmh = 220, ZeroToOneHundredKmh = 7, Gears = 5, FuelTankL = 60, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_t16_mech_1", Manufacturer = "Peugeot", Name = "205 T16", Variant = "", PerformanceRating = 9.8, Categories = "Road:Youngtimer:ICE", DriveLayout = "AWD", EngineLayout = "Mid", Engine = "Turbo Charged", Body = "Hatch Back", RacingClass = "", Year = 1990, PowerPs = 200, TorqueNm = 255, DisplacementL = 1.8, Cylinders = 4, WeightKg = 1145, MaxSpeedKmh = 210, ZeroToOneHundredKmh = 6, Gears = 5, FuelTankL = 90, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_gt4csmr_mech_1", Manufacturer = "Porsche", Name = "718 Cayman GT4 Clubsport", Variant = "", PerformanceRating = 16.3, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "GT4", Year = 2019, PowerPs = 420, TorqueNm = 425, DisplacementL = 3.8, Cylinders = 6, WeightKg = 1295, MaxSpeedKmh = 280, ZeroToOneHundredKmh = 3.4, Gears = 7, FuelTankL = 115, BatteryKwh = null, MaxRpm = 7800 },
        new() { ModelId = "preset_718gt4rs_mech_1", Manufacturer = "Porsche", Name = "718 Gaymane GT4 RS", Variant = "718 Gaymane GT4 RS", PerformanceRating = 12.7, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 2022, PowerPs = 500, TorqueNm = 450, DisplacementL = 4, Cylinders = 6, WeightKg = 1490, MaxSpeedKmh = 315, ZeroToOneHundredKmh = 3.4, Gears = 7, FuelTankL = 64, BatteryKwh = null, MaxRpm = 9000 },
        new() { ModelId = "preset_718gt4rs_mech_2", Manufacturer = "Porsche", Name = "718 Gaymane GT4 RS", Variant = "718 Gaymane GT4 RS with Weissach-package", PerformanceRating = 12.7, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Mid", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 2022, PowerPs = 500, TorqueNm = 450, DisplacementL = 4, Cylinders = 6, WeightKg = 1490, MaxSpeedKmh = 315, ZeroToOneHundredKmh = 3.4, Gears = 7, FuelTankL = 64, BatteryKwh = null, MaxRpm = 9000 },
        new() { ModelId = "preset_gt2rscs_mech_1", Manufacturer = "Porsche", Name = "911 GT2 RS", Variant = "", PerformanceRating = 18.2, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Rear", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "GT2", Year = 2023, PowerPs = 700, TorqueNm = 630, DisplacementL = 3.8, Cylinders = 6, WeightKg = 1315, MaxSpeedKmh = 300, ZeroToOneHundredKmh = 2.9, Gears = 7, FuelTankL = 120, BatteryKwh = null, MaxRpm = 7200 },
        new() { ModelId = "preset_992c_mech_1", Manufacturer = "Porsche", Name = "911 GT3 Cup (992)", Variant = "Carrera Cup ABS & TC", PerformanceRating = 17.3, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Rear", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "Cup", Year = 2021, PowerPs = 510, TorqueNm = 474, DisplacementL = 4, Cylinders = 6, WeightKg = 1260, MaxSpeedKmh = 293, ZeroToOneHundredKmh = 2.9, Gears = 6, FuelTankL = 112, BatteryKwh = null, MaxRpm = 8750 },
        new() { ModelId = "preset_992c_mech_2", Manufacturer = "Porsche", Name = "911 GT3 Cup (992)", Variant = "Carrera Cup ABS", PerformanceRating = 17.3, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Rear", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "Cup", Year = 2021, PowerPs = 510, TorqueNm = 474, DisplacementL = 4, Cylinders = 6, WeightKg = 1260, MaxSpeedKmh = 293, ZeroToOneHundredKmh = 2.9, Gears = 6, FuelTankL = 112, BatteryKwh = null, MaxRpm = 8750 },
        new() { ModelId = "preset_992c_mech_3", Manufacturer = "Porsche", Name = "911 GT3 Cup (992)", Variant = "Carrera Cup Base", PerformanceRating = 17.3, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Rear", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "Cup", Year = 2021, PowerPs = 510, TorqueNm = 474, DisplacementL = 4, Cylinders = 6, WeightKg = 1260, MaxSpeedKmh = 293, ZeroToOneHundredKmh = 2.9, Gears = 6, FuelTankL = 112, BatteryKwh = null, MaxRpm = 8750 },
        new() { ModelId = "preset_992ren_mech_1", Manufacturer = "Porsche", Name = "911 GTR R Rennsport (992)", Variant = "GT3 R Rennsport GT3", PerformanceRating = 19.8, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Rear", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "GT3", Year = 2022, PowerPs = 540, TorqueNm = 510, DisplacementL = 4.2, Cylinders = 6, WeightKg = 1250, MaxSpeedKmh = 290, ZeroToOneHundredKmh = 2.9, Gears = 6, FuelTankL = 117, BatteryKwh = null, MaxRpm = 9400 },
        new() { ModelId = "preset_992ren_mech_2", Manufacturer = "Porsche", Name = "911 GTR R Rennsport (992)", Variant = "GT3 R Rennsport Unrestricted", PerformanceRating = 20.3, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Rear", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "GT3", Year = 2022, PowerPs = 540, TorqueNm = 510, DisplacementL = 4.2, Cylinders = 6, WeightKg = 1250, MaxSpeedKmh = 290, ZeroToOneHundredKmh = 2.9, Gears = 6, FuelTankL = 117, BatteryKwh = null, MaxRpm = 9400 },
        new() { ModelId = "preset_gt3rs_mech_1", Manufacturer = "Porsche", Name = "911 GT3 RS (992)", Variant = "GT3 RS (992)", PerformanceRating = 16.5, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Rear", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 2021, PowerPs = 525, TorqueNm = 455, DisplacementL = 4, Cylinders = 6, WeightKg = 1450, MaxSpeedKmh = 296, ZeroToOneHundredKmh = 3.2, Gears = 7, FuelTankL = 90, BatteryKwh = null, MaxRpm = 8500 },
        new() { ModelId = "preset_gt3rs_mech_2", Manufacturer = "Porsche", Name = "911 GT3 RS (992)", Variant = "GT3 RS (992) with Wiessach-package", PerformanceRating = 16.6, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Rear", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 2021, PowerPs = 525, TorqueNm = 455, DisplacementL = 4, Cylinders = 6, WeightKg = 1430, MaxSpeedKmh = 296, ZeroToOneHundredKmh = 3.2, Gears = 7, FuelTankL = 90, BatteryKwh = null, MaxRpm = 8500 },
        new() { ModelId = "preset_964_mech_1", Manufacturer = "Porsche", Name = "911 Turbo 3.6 (964)", Variant = "964 Turbo", PerformanceRating = 12.3, Categories = "Road:Youngtimer:ICE", DriveLayout = "RWD", EngineLayout = "Rear", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "", Year = 1993, PowerPs = 350, TorqueNm = 520, DisplacementL = 3.5, Cylinders = 6, WeightKg = 1460, MaxSpeedKmh = 280, ZeroToOneHundredKmh = 4.8, Gears = 5, FuelTankL = 92, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_964_mech_2", Manufacturer = "Porsche", Name = "911 Turbo 3.6 (964)", Variant = "964 Turbo Power Package", PerformanceRating = 12.4, Categories = "Road:Youngtimer:ICE", DriveLayout = "RWD", EngineLayout = "Rear", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "", Year = 1993, PowerPs = 385, TorqueNm = 520, DisplacementL = 3.5, Cylinders = 6, WeightKg = 1460, MaxSpeedKmh = 280, ZeroToOneHundredKmh = 4.8, Gears = 5, FuelTankL = 92, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_935_mech_1", Manufacturer = "Porsche", Name = "935", Variant = "", PerformanceRating = 17.9, Categories = "Racing:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Rear", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "GT2", Year = 2019, PowerPs = 700, TorqueNm = 630, DisplacementL = 3.8, Cylinders = 6, WeightKg = 1315, MaxSpeedKmh = 300, ZeroToOneHundredKmh = 299, Gears = 7, FuelTankL = 120, BatteryKwh = null, MaxRpm = 7200 },
        new() { ModelId = "preset_r5gt_mech_1", Manufacturer = "Renault", Name = "5 GT Turbo", Variant = "", PerformanceRating = 8.5, Categories = "Road:Youngtimer:ICE", DriveLayout = "FWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Hatch Back", RacingClass = "", Year = 1990, PowerPs = 120, TorqueNm = 165, DisplacementL = 1.4, Cylinders = 4, WeightKg = 863, MaxSpeedKmh = 204, ZeroToOneHundredKmh = 8, Gears = 5, FuelTankL = 50, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_gr86_mech_1", Manufacturer = "Toyota", Name = "GR86", Variant = "GR86 Premium", PerformanceRating = 8.9, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 2021, PowerPs = 235, TorqueNm = 250, DisplacementL = 2.4, Cylinders = 4, WeightKg = 1280, MaxSpeedKmh = 225, ZeroToOneHundredKmh = 6.3, Gears = 6, FuelTankL = 50, BatteryKwh = null, MaxRpm = 7400 },
        new() { ModelId = "preset_gr86_mech_2", Manufacturer = "Toyota", Name = "GR86", Variant = "GR86 Trueno Edition, Performance Package", PerformanceRating = 8.9, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 2021, PowerPs = 235, TorqueNm = 250, DisplacementL = 2.4, Cylinders = 4, WeightKg = 1270, MaxSpeedKmh = 225, ZeroToOneHundredKmh = 6.3, Gears = 6, FuelTankL = 50, BatteryKwh = null, MaxRpm = 7400 },
        new() { ModelId = "preset_gr86_mech_3", Manufacturer = "Toyota", Name = "GR86", Variant = "GR86 Hakone Edition, Performance Package", PerformanceRating = 8.9, Categories = "Road:Modern:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 2021, PowerPs = 235, TorqueNm = 250, DisplacementL = 2.4, Cylinders = 4, WeightKg = 1270, MaxSpeedKmh = 225, ZeroToOneHundredKmh = 6.3, Gears = 6, FuelTankL = 50, BatteryKwh = null, MaxRpm = 7400 },
        new() { ModelId = "preset_ae86_mech_1", Manufacturer = "Toyota", Name = "Sprinter Trueno 1600GT - Apex (AE86)", Variant = "GT-Apex Zenki", PerformanceRating = 8.3, Categories = "Road:Vintage:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 1984, PowerPs = 130, TorqueNm = 149, DisplacementL = 1.6, Cylinders = 4, WeightKg = 920, MaxSpeedKmh = 180, ZeroToOneHundredKmh = 8.5, Gears = 5, FuelTankL = 50, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_ae86_mech_2", Manufacturer = "Toyota", Name = "Sprinter Trueno 1600GT - Apex (AE86)", Variant = "GT-Apex Kouki", PerformanceRating = 8.3, Categories = "Road:Vintage:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 1984, PowerPs = 130, TorqueNm = 149, DisplacementL = 1.6, Cylinders = 4, WeightKg = 920, MaxSpeedKmh = 180, ZeroToOneHundredKmh = 8.5, Gears = 5, FuelTankL = 50, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_ae86_mech_3", Manufacturer = "Toyota", Name = "Sprinter Trueno 1600GT - Apex (AE86)", Variant = "GT-Apex Black Limited Edition", PerformanceRating = 8.3, Categories = "Road:Vintage:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 1984, PowerPs = 130, TorqueNm = 149, DisplacementL = 1.6, Cylinders = 4, WeightKg = 920, MaxSpeedKmh = 180, ZeroToOneHundredKmh = 8.5, Gears = 5, FuelTankL = 50, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_ae86_mech_4", Manufacturer = "Toyota", Name = "Sprinter Trueno 1600GT - Apex (AE86)", Variant = "GT-Apex Zenki Anime Tribute", PerformanceRating = 9.6, Categories = "Road:Vintage:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Coupe", RacingClass = "", Year = 1984, PowerPs = 250, TorqueNm = 192, DisplacementL = 1.6, Cylinders = 4, WeightKg = 920, MaxSpeedKmh = 240, ZeroToOneHundredKmh = 6, Gears = 6, FuelTankL = 50, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_supramkiv_mech_1", Manufacturer = "Toyota", Name = "Supra MK IV", Variant = "RZ 3.0 Turbo", PerformanceRating = 10.1, Categories = "Road:Youngtimer:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "", Year = 1998, PowerPs = 280, TorqueNm = 451, DisplacementL = 3, Cylinders = 6, WeightKg = 1510, MaxSpeedKmh = 254, ZeroToOneHundredKmh = 5.1, Gears = 6, FuelTankL = 70, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_supramkiv_mech_2", Manufacturer = "Toyota", Name = "Supra MK IV", Variant = "Drift Tune Step", PerformanceRating = 13, Categories = "Road:Youngtimer:ICE", DriveLayout = "RWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Coupe", RacingClass = "", Year = 1998, PowerPs = 600, TorqueNm = 700, DisplacementL = 3, Cylinders = 6, WeightKg = 1510, MaxSpeedKmh = 280, ZeroToOneHundredKmh = 4, Gears = 6, FuelTankL = 70, BatteryKwh = null, MaxRpm = 8000 },
        new() { ModelId = "preset_mk8gti_mech_1", Manufacturer = "Volkswagen", Name = "Golf 8 GTI", Variant = "", PerformanceRating = 10.8, Categories = "Road:Modern:ICE", DriveLayout = "FWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Hatch Back", RacingClass = "", Year = 2021, PowerPs = 300, TorqueNm = 400, DisplacementL = 2, Cylinders = 4, WeightKg = 1388, MaxSpeedKmh = 270, ZeroToOneHundredKmh = 5.9, Gears = 7, FuelTankL = 50, BatteryKwh = null, MaxRpm = 6400 },
        new() { ModelId = "preset_mk8r_mech_1", Manufacturer = "Volkswagen", Name = "Golf 8 R", Variant = "", PerformanceRating = 10, Categories = "Road:Modern:ICE", DriveLayout = "AWD", EngineLayout = "Front", Engine = "Turbo Charged", Body = "Hatch Back", RacingClass = "", Year = 2021, PowerPs = 320, TorqueNm = 420, DisplacementL = 2, Cylinders = 4, WeightKg = 1553, MaxSpeedKmh = 250, ZeroToOneHundredKmh = 4.5, Gears = 7, FuelTankL = 55, BatteryKwh = null, MaxRpm = null },
        new() { ModelId = "preset_gtimk1_mech_1", Manufacturer = "Volkswagen", Name = "Golf GTI Mk1", Variant = "", PerformanceRating = 7.4, Categories = "Road:Vintage:ICE", DriveLayout = "FWD", EngineLayout = "Front", Engine = "Naturally Aspirated", Body = "Hatch Back", RacingClass = "", Year = 1978, PowerPs = 110, TorqueNm = 140, DisplacementL = 1.6, Cylinders = 4, WeightKg = 810, MaxSpeedKmh = 180, ZeroToOneHundredKmh = 9, Gears = 4, FuelTankL = 40, BatteryKwh = null, MaxRpm = null }
    ];

    public static AceCarInfoProvider Instance => singletonInstance ??= new AceCarInfoProvider();

    public AceCarInfo? FindByModelId(string modelId)
    {
        return this.cars.FirstOrDefault(c => c.ModelId == modelId);
    }

    public AceCarInfo? FindByName(string name)
    {
        return this.cars.FirstOrDefault(c => c.Name == name);
    }

    public AceCarInfo? FindByAceName(string aceName)
    {
        return this.cars.FirstOrDefault(c => c.AceName == aceName);
    }

    public IReadOnlyCollection<AceCarInfo> GetCarInfos()
    {
        return this.cars.AsReadOnly();
    }

    public IReadOnlyCollection<AceCarInfo> GetCarInfosForManufacturer(string manufacturer)
    {
        return this.cars.Where(c => c.Manufacturer == manufacturer)
                         .ToList()
                         .AsReadOnly();
    }

    public IReadOnlyCollection<string> GetManufacturers()
    {
        return this.cars.Select(c => c.Manufacturer)
                         .Distinct()
                         .OrderBy(m => m)
                         .ToList()
                         .AsReadOnly();
    }
}
