<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>


	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.8" />
		<PackageReference Include="NLog.Extensions.Logging" Version="6.0.3" />
		<PackageReference Include="System.Reactive" Version="6.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SimRacingSdk.Lmu.Core\SimRacingSdk.Lmu.Core.csproj" />
		<ProjectReference Include="..\SimRacingSdk.Lmu.Monitor\SimRacingSdk.Lmu.Monitor.csproj" />
		<ProjectReference Include="..\SimRacingSdk.Lmu.SharedMemory\SimRacingSdk.Lmu.SharedMemory.csproj" />
		<ProjectReference Include="..\SimRacingSdk.LogViewer\SimRacingSdk.LogViewer.csproj" />
		<ProjectReference Include="..\SimRacingSdk.Wpf.Shared\SimRacingSdk.Wpf.Shared.csproj" />
	</ItemGroup>


  <ItemGroup>
    <None Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CarExplorer\CarExplorerWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="TrackExplorer\TrackExplorerWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
