using SimRacingSdk.Pmr.Core.Abstractions;
using SimRacingSdk.Pmr.Core.Models;

namespace SimRacingSdk.Pmr.Core;

public class PmrCarInfoProvider : IPmrCarInfoProvider
{
    private static PmrCarInfoProvider? singletonInstance;

    private readonly List<PmrCarInfo> cars =
    [
        new() { ClassString = "class_LMDh", DescriptionKey = "cardesc_acuraarx", EngineName = "2.4L V6 Twin Turbo", FuelCapacityLitres = null, IconFileName = "Acura", Id = "ID_Acura_ARX-06_2023", Layout = "Mid Engine - RWD", Manufacturer = "Acura", Name = "ARX-06", PowerBhp = 670, Region = "Europe", TorqueNm = 688, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", VehiclePath = "Acura_ARX-06_2023", WeightKg = 1030, Year = 2023 },
        new() { ClassString = "class_gt3", DescriptionKey = "cardesc_acuransxgt3", EngineName = "3.5L V6 Twin Turbo", FuelCapacityLitres = 90.5999984741211, IconFileName = "Acura", Id = "ID_HONDA_NSX_GT3", Layout = "Mid Engine - RWD", Manufacturer = "Acura", Name = "NSX GT3 Evo 22", PowerBhp = 520, Region = "Europe", TorqueNm = 640, Transmission = "6-Speed Paddle", VehicleClass = "GT3", VehiclePath = "Honda_NSX_GT3", WeightKg = 1290, Year = 2022 },
        new() { ClassString = "class_gt4", DescriptionKey = "cardesc_alpinea110gt4", EngineName = "1.8L L4 Turbo", FuelCapacityLitres = 95, IconFileName = "Alpine", Id = "ID_Alpine_A110_GT4_2020", Layout = "Mid Engine - RWD", Manufacturer = "Alpine", Name = "A110 GT4", PowerBhp = 360, Region = "Europe", TorqueNm = 488, Transmission = "6-Speed Paddle", VehicleClass = "GT4", VehiclePath = "Alpine_A110_GT4_2020", WeightKg = 1160, Year = 2020 },
        new() { ClassString = "class_LMDh", DescriptionKey = "cardesc_alpinea424", EngineName = "3.4L V6 Twin Turbo", FuelCapacityLitres = null, IconFileName = "Alpine", Id = "ID_Alpine_A424_2024", Layout = "Mid Engine - RWD", Manufacturer = "Alpine", Name = "A424 Beta", PowerBhp = 670, Region = "Europe", TorqueNm = 670, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", VehiclePath = "Alpine_A424_2024", WeightKg = 1030, Year = 2024 },
        new() { ClassString = "class_GT3", DescriptionKey = "cardesc_astongt3_2025", EngineName = "4.0L V8 Twin Turbo", FuelCapacityLitres = 90.5999984741211, IconFileName = "Aston Martin", Id = "ID_Aston_Martin_Vantage_GT3_Evo", Layout = "Front Engine - RWD", Manufacturer = "Aston Martin", Name = "AMR Vantage GT3", PowerBhp = 508, Region = "Europe", TorqueNm = 690, Transmission = "6-Speed Paddle", VehicleClass = "GT3", VehiclePath = "Aston_Martin_Vantage_GT3_Evo", WeightKg = 1325, Year = 2024 },
        new() { ClassString = "class_GT3", DescriptionKey = "cardesc_astongt3_2022", EngineName = "4.0L V8 Twin Turbo", FuelCapacityLitres = 90.5999984741211, IconFileName = "Aston Martin", Id = "ID_Aston_Martin_Vantage_GT3", Layout = "Front Engine - RWD", Manufacturer = "Aston Martin", Name = "AMR Vantage GT3 2022", PowerBhp = 508, Region = "Europe", TorqueNm = 690, Transmission = "6-Speed Paddle", VehicleClass = "GT3", VehiclePath = "Aston_Martin_Vantage_GT3", WeightKg = 1325, Year = 2022 },
        new() { ClassString = "class_GT4", DescriptionKey = "cardesc_astonamrgt4", EngineName = "4.0L V8 Twin Turbo", FuelCapacityLitres = 120, IconFileName = "Aston Martin", Id = "ID_Aston_Martin_Vantage_AMR_GT4", Layout = "Front Engine - RWD", Manufacturer = "Aston Martin", Name = "AMR Vantage GT4", PowerBhp = 475, Region = "Europe", TorqueNm = 690, Transmission = "6-Speed Paddle", VehicleClass = "GT4", VehiclePath = "Aston_Martin_Vantage_AMR_GT4", WeightKg = 1400, Year = 2020 },
        new() { ClassString = "class_gt", DescriptionKey = "cardesc_astondbr9", EngineName = "6.0L V12", FuelCapacityLitres = 75.51000213623047, IconFileName = "Aston Martin", Id = "ID_Aston_Martin_DBR9_2005", Layout = "Front Engine - RWD", Manufacturer = "Aston Martin", Name = "DBR9", PowerBhp = 625, Region = "Europe", TorqueNm = 700, Transmission = "6-Speed Sequential", VehicleClass = "GT", VehiclePath = "Aston_Martin_DBR9_2005", WeightKg = 1170, Year = 2005 },
        new() { ClassString = "class_LMDh", DescriptionKey = "cardesc_astonvalkyrie", EngineName = "6.5L V12", FuelCapacityLitres = 110, IconFileName = "Aston Martin", Id = "ID_Aston_Martin_Valkyrie_LMH_2025", Layout = "Mid Engine - RWD", Manufacturer = "Aston Martin", Name = "Valkyrie Hypercar", PowerBhp = 680, Region = "Europe", TorqueNm = 750, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", VehiclePath = "Aston_Martin_Valkyrie_LMH_2025", WeightKg = 1030, Year = 2025 },
        new() { ClassString = "class_gto", DescriptionKey = "cardesc_audi90imsa", EngineName = "2.2L L5 Turbo", FuelCapacityLitres = 75.51000213623047, IconFileName = "Audi", Id = "ID_Audi_90_IMSA_GTO_1989", Layout = "Front Engine - 4WD", Manufacturer = "Audi", Name = "90 IMSA GTO", PowerBhp = 710, Region = "Americas", TorqueNm = 720, Transmission = "5-Speed Manual", VehicleClass = "GTO", VehiclePath = "Audi_90_IMSA_GTO_1989", WeightKg = 1207, Year = 1989 },
        new() { ClassString = "class_LMP", DescriptionKey = "cardesc_audir8lmp", EngineName = "3.6L V8 Twin Turbo", FuelCapacityLitres = 90, IconFileName = "Audi", Id = "ID_Audi_R8_LMP900_2002", Layout = "Mid Engine - RWD", Manufacturer = "Audi", Name = "R8 (LMP900)", PowerBhp = 635, Region = "Europe", TorqueNm = 680, Transmission = "6-Speed Paddle", VehicleClass = "LMP", VehiclePath = "Audi_R8_LMP900_2002", WeightKg = 911, Year = 2002 },
        new() { ClassString = "class_gt3", DescriptionKey = "cardesc_audir8gt3", EngineName = "5.2L V10", FuelCapacityLitres = 90.5999984741211, IconFileName = "Audi", Id = "ID_Audi_R8_LMS_GT3_Evo", Layout = "Mid Engine - RWD", Manufacturer = "Audi", Name = "R8 GT3 Evo II", PowerBhp = 515, Region = "Europe", TorqueNm = 580, Transmission = "6-Speed Paddle", VehicleClass = "GT3", VehiclePath = "Audi_R8_LMS_GT3_Evo", WeightKg = 1310, Year = 2022 },
        new() { ClassString = "class_gt4", DescriptionKey = "cardesc_audir8gt4", EngineName = "5.2L V10", FuelCapacityLitres = 113, IconFileName = "Audi", Id = "ID_Audi_R8_LMS_GT4_Evo", Layout = "Mid Engine - RWD", Manufacturer = "Audi", Name = "R8 LMS GT4 Evo", PowerBhp = 440, Region = "Europe", TorqueNm = 480, Transmission = "7-Speed Paddle", VehicleClass = "GT4", VehiclePath = "Audi_R8_LMS_GT4_Evo", WeightKg = 1485, Year = 2020 },
        new() { ClassString = "class_LMDh", DescriptionKey = "cardesc_bmwmhybrid", EngineName = "4.0L V8 Twin Turbo", FuelCapacityLitres = null, IconFileName = "BMW", Id = "ID_BMW_M_Hybrid_V8", Layout = "Mid Engine - RWD", Manufacturer = "BMW", Name = "M Hybrid V8", PowerBhp = 670, Region = "Europe", TorqueNm = 700, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", VehiclePath = "BMW_M_Hybrid_V8", WeightKg = 1030, Year = 2023 },
        new() { ClassString = "class_n-gt", DescriptionKey = "cardesc_bmwm3gtr", EngineName = "4.0L V8", FuelCapacityLitres = 67.5, IconFileName = "BMW", Id = "ID_BMW_M3_E46", Layout = "Front Engine - RWD", Manufacturer = "BMW", Name = "M3 GTR (E46)", PowerBhp = 450, Region = "Europe", TorqueNm = 365, Transmission = "6-Speed Sequential", VehicleClass = "N-GT", VehiclePath = "BMW_M3_E46_GTR", WeightKg = 1120, Year = 2004 },
        new() { ClassString = "class_gt3", DescriptionKey = "cardesc_bmwm4gt3", EngineName = "3.0L L6 Twin Turbo", FuelCapacityLitres = 90.5999984741211, IconFileName = "BMW", Id = "ID_BMW_M4_GT3", Layout = "Front Engine - RWD", Manufacturer = "BMW", Name = "M4 GT3 EVO", PowerBhp = 525, Region = "Europe", TorqueNm = 650, Transmission = "6-Speed Paddle", VehicleClass = "GT3", VehiclePath = "BMW_M4_GT3", WeightKg = 1360, Year = 2025 },
        new() { ClassString = "class_gt4", DescriptionKey = "cardesc_bmwm4gt4", EngineName = "3.0L L6 Twin Turbo", FuelCapacityLitres = 120, IconFileName = "BMW", Id = "ID_BMW_M4_GT4", Layout = "Front Engine - RWD", Manufacturer = "BMW", Name = "M4 GT4 EVO", PowerBhp = 518, Region = "Europe", TorqueNm = 550, Transmission = "7-Speed Paddle", VehicleClass = "GT4", VehiclePath = "BMW_M4_GT4", WeightKg = 1430, Year = 2025 },
        new() { ClassString = "class_LMP", DescriptionKey = "cardesc_bmwv12lmr", EngineName = "6.0L V12", FuelCapacityLitres = 90, IconFileName = "BMW", Id = "ID_BMW_V12_LMR", Layout = "Mid Engine - RWD", Manufacturer = "BMW", Name = "V12 LMR", PowerBhp = 590, Region = "Europe", TorqueNm = 678, Transmission = "6-Speed Sequential", VehicleClass = "LMP", VehiclePath = "BMW_V12_LMR", WeightKg = 914, Year = 1999 },
        new() { ClassString = "class_LMP", DescriptionKey = "cardesc_cadillacnorthstar", EngineName = "4.0L V8 Twin Turbo", FuelCapacityLitres = 75.51000213623047, IconFileName = "Cadillac", Id = "ID_Cadillac_Northstar_LMP900", Layout = "Mid Engine - RWD", Manufacturer = "Cadillac", Name = "Northstar LMP-02", PowerBhp = 620, Region = "Americas", TorqueNm = 700, Transmission = "6-Speed Paddle", VehicleClass = "LMP", VehiclePath = "Cadillac_Northstar_LMP900", WeightKg = 916, Year = 2002 },
        new() { ClassString = "class_LMDh", DescriptionKey = "cardesc_cadillacvseriesr", EngineName = "5.5L V8", FuelCapacityLitres = null, IconFileName = "Cadillac", Id = "ID_Cadillac_V_SeriesR", Layout = "Mid Engine - RWD", Manufacturer = "Cadillac", Name = "V-Series.R", PowerBhp = 670, Region = "Americas", TorqueNm = 740, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", VehiclePath = "Cadillac_V_SeriesR", WeightKg = 1030, Year = 2023 },
        new() { ClassString = "class_GTO", DescriptionKey = "cardesc_camarogto", EngineName = "6.0L V8", FuelCapacityLitres = 75.51000213623047, IconFileName = "Chevrolet", Id = "ID_Chevrolet_Camaro_Z28_GTO_1989", Layout = "Front Engine - RWD", Manufacturer = "Chevrolet", Name = "Camaro Z28 GTO", PowerBhp = 600, Region = "Americas", TorqueNm = 666, Transmission = "5-Speed Manual", VehicleClass = "GTO", VehiclePath = "Chevrolet_Camaro_Z28_GTO_1989", WeightKg = 1225, Year = 1989 },
        new() { ClassString = "class_GT4", DescriptionKey = "cardesc_camarogt4", EngineName = "6.2L V8", FuelCapacityLitres = 87, IconFileName = "Chevrolet", Id = "ID_Chevrolet_Camaro_ZL-1_GT4_2017", Layout = "Front Engine - RWD", Manufacturer = "Chevrolet", Name = "Camaro ZL-1 GT4.R", PowerBhp = 440, Region = "Americas", TorqueNm = 575, Transmission = "6-Speed Paddle", VehicleClass = "GT4", VehiclePath = "Chevrolet_Camaro_ZL-1_GT4_2017", WeightKg = 1470, Year = 2017 },
        new() { ClassString = "class_gt", DescriptionKey = "cardesc_corvettec5r", EngineName = "7.0L V8", FuelCapacityLitres = 75.51000213623047, IconFileName = "Chevrolet", Id = "ID_Chevrolet_Corvette_C5R", Layout = "Front Engine - RWD", Manufacturer = "Chevrolet", Name = "Corvette C5.R", PowerBhp = 610, Region = "Americas", TorqueNm = 770, Transmission = "6-Speed Manual", VehicleClass = "GT", VehiclePath = "Chevrolet_Corvette_C5R", WeightKg = 1270, Year = 2004 },
        new() { ClassString = "class_gt", DescriptionKey = "cardesc_corvettec6r", EngineName = "7.0L V8", FuelCapacityLitres = 75.51000213623047, IconFileName = "Chevrolet", Id = "ID_Chevrolet_Corvette_C6R", Layout = "Front Engine - RWD", Manufacturer = "Chevrolet", Name = "Corvette C6.R", PowerBhp = 570, Region = "Americas", TorqueNm = 840, Transmission = "6-Speed Sequential", VehicleClass = "GT", VehiclePath = "Chevrolet_Corvette_C6R", WeightKg = 1100, Year = 2005 },
        new() { ClassString = "class_gt3", DescriptionKey = "cardesc_corvettegt3", EngineName = "5.5L V8", FuelCapacityLitres = 90.5999984741211, IconFileName = "Chevrolet", Id = "ID_Chevrolet_Corvette_Z06_GT3_2024", Layout = "Mid Engine - RWD", Manufacturer = "Chevrolet", Name = "Corvette Z06 GT3.R", PowerBhp = 530, Region = "Americas", TorqueNm = 630, Transmission = "6-Speed Paddle", VehicleClass = "GT3", VehiclePath = "Chevrolet_Corvette_Z06_GT3_2024", WeightKg = 1345, Year = 2023 },
        new() { ClassString = "class_gt", DescriptionKey = "cardesc_vipergtsr", EngineName = "8.0L V10", FuelCapacityLitres = 75.51000213623047, IconFileName = "Chrysler", Id = "ID_Chrysler_Viper_GTS-R", Layout = "Front Engine - RWD", Manufacturer = "Chrysler", Name = "Viper GTS-R", PowerBhp = 620, Region = "Americas", TorqueNm = 780, Transmission = "6-Speed Manual", VehicleClass = "GT", VehiclePath = "Chrysler_Viper_GTS-R", WeightKg = 1100, Year = 2003 },
        new() { ClassString = "class_n-gt", DescriptionKey = "cardesc_vipercomp", EngineName = "8.0L V10", FuelCapacityLitres = 67.5, IconFileName = "Dodge", Id = "ID_Dodge_Viper_CC", Layout = "Front Engine - RWD", Manufacturer = "Dodge", Name = "Viper Competition Coupe", PowerBhp = 520, Region = "Americas", TorqueNm = 730, Transmission = "6-Speed Manual", VehicleClass = "N-GT", VehiclePath = "Dodge_Viper_CC", WeightKg = 1415, Year = 2004 },
        new() { ClassString = "class_gt3", DescriptionKey = "cardesc_mustanggt3", EngineName = "5.4L V8", FuelCapacityLitres = 90.5999984741211, IconFileName = "Ford", Id = "ID_Ford_Mustang_GT3_2023", Layout = "Front Engine - RWD", Manufacturer = "Ford", Name = "Mustang GT3", PowerBhp = 520, Region = "Americas", TorqueNm = 660, Transmission = "6-Speed Paddle", VehicleClass = "GT3", VehiclePath = "Ford_Mustang_GT3_2023", WeightKg = 1300, Year = 2023 },
        new() { ClassString = "class_gt4", DescriptionKey = "cardesc_mustanggt4", EngineName = "5.0L V8", FuelCapacityLitres = 100, IconFileName = "Ford", Id = "ID_Ford_Mustang_GT4_2024", Layout = "Front Engine - RWD", Manufacturer = "Ford", Name = "Mustang GT4", PowerBhp = 500, Region = "Americas", TorqueNm = 580, Transmission = "6-Speed Paddle", VehicleClass = "GT4", VehiclePath = "Ford_Mustang_GT4_2024", WeightKg = 1390, Year = 2024 },
        new() { ClassString = "class_n-gt", DescriptionKey = "cardesc_gilletvertigo", EngineName = "3.0L V6", FuelCapacityLitres = 67.5, IconFileName = "Gillet", Id = "ID_Gillet_Vertigo", Layout = "Front Engine - RWD", Manufacturer = "Gillet", Name = "Vertigo", PowerBhp = 345, Region = "Europe", TorqueNm = 425, Transmission = "6-Speed Sequential", VehicleClass = "N-GT", VehiclePath = "Gillet_Vertigo_2004", WeightKg = 806, Year = 2004 },
        new() { ClassString = "class_grc", DescriptionKey = "cardesc_jaguarxjr9", EngineName = "7.0L V12", FuelCapacityLitres = 100, IconFileName = "Jaguar", Id = "ID_Jaguar_XJR-9", Layout = "Mid Engine - RWD", Manufacturer = "Jaguar", Name = "XJR-9", PowerBhp = 750, Region = "Europe", TorqueNm = 828, Transmission = "5-Speed Manual", VehicleClass = "Group C", VehiclePath = "Jaguar_XJR-9", WeightKg = 880, Year = 1990 },
        new() { ClassString = "class_gt3", DescriptionKey = "cardesc_lamborghinihuracangt3", EngineName = "5.2L V10", FuelCapacityLitres = 90.5999984741211, IconFileName = "Lamborghini", Id = "ID_Lamborghini_Huracan_GT3_Evo_2022", Layout = "Mid Engine - RWD", Manufacturer = "Lamborghini", Name = "Huracán GT3 Evo2", PowerBhp = 515, Region = "Europe", TorqueNm = 580, Transmission = "6-Speed Paddle", VehicleClass = "GT3", VehiclePath = "Lamborghini_Huracan_GT3_Evo_2022", WeightKg = 1280, Year = 2022 },
        new() { ClassString = "class_gt", DescriptionKey = "cardesc_lamborghinimurcielagorgt", EngineName = "6.0L V12", FuelCapacityLitres = 75.51000213623047, IconFileName = "Lamborghini", Id = "ID_Lamborghini_Murcielago_R-GT_2004", Layout = "Mid Engine - RWD", Manufacturer = "Lamborghini", Name = "Murcielago R-GT", PowerBhp = 600, Region = "Europe", TorqueNm = 650, Transmission = "6-Speed Sequential", VehicleClass = "GT", VehiclePath = "Lamborghini_Murcielago_R-GT_2004", WeightKg = 1100, Year = 2004 },
        new() { ClassString = "class_LMDh", DescriptionKey = "cardesc_lamborghinisc63", EngineName = "3.8L V8 Twin Turbo", FuelCapacityLitres = null, IconFileName = "Lamborghini", Id = "ID_Lamborghini_SC63_LMDh_2024", Layout = "Mid Engine - RWD", Manufacturer = "Lamborghini", Name = "SC63 LMDh", PowerBhp = 670, Region = "Europe", TorqueNm = 710, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", VehiclePath = "Lamborghini_SC63_LMDh_2024", WeightKg = 1030, Year = 2024 },
        new() { ClassString = "class_gt", DescriptionKey = "cardesc_listerstormgt", EngineName = "7.0L V12", FuelCapacityLitres = 75.51000213623047, IconFileName = "Lister", Id = "ID_Lister_Storm_GT", Layout = "Front Engine - RWD", Manufacturer = "Lister", Name = "Storm GT", PowerBhp = 575, Region = "Europe", TorqueNm = 780, Transmission = "6-Speed Sequential", VehicleClass = "GT", VehiclePath = "Lister_storm_gt", WeightKg = 1125, Year = 2004 },
        new() { ClassString = "class_Sports Car 70", DescriptionKey = "cardesc_lolat70", EngineName = "5.0L V8", FuelCapacityLitres = 120, IconFileName = "Lola", Id = "ID_Lola_T70_MK3B_1970", Layout = "Mid Engine - RWD", Manufacturer = "Lola", Name = "T70 Mk3B GT", PowerBhp = 450, Region = "Europe", TorqueNm = 485, Transmission = "5-Speed Manual", VehicleClass = "Sports Car 70", VehiclePath = "Lola_T70_MK3B_1970", WeightKg = 845, Year = 1970 },
        new() { ClassString = "class_gt1", DescriptionKey = "cardesc_lotuselise", EngineName = "6.0L V8", FuelCapacityLitres = 100, IconFileName = "Lotus", Id = "ID_Lotus_Elise_GT1_1997", Layout = "Mid Engine - RWD", Manufacturer = "Lotus", Name = "Elise GT1", PowerBhp = 575, Region = "Europe", TorqueNm = 625, Transmission = "6-Speed Sequential", VehicleClass = "GT1", VehiclePath = "Lotus_Elise_GT1_1997", WeightKg = 972, Year = 1997 },
        new() { ClassString = "class_n-gt", DescriptionKey = "cardesc_marcosmantara", EngineName = "6.0L V8", FuelCapacityLitres = 75.51000213623047, IconFileName = "Marcos", Id = "ID_Marcos_Mantara_LM600_GT2_2004", Layout = "Front Engine - RWD", Manufacturer = "Marcos", Name = "Mantara LM600", PowerBhp = 480, Region = "Europe", TorqueNm = 650, Transmission = "6-Speed Sequential", VehicleClass = "N-GT", VehiclePath = "Marcos_Mantara_LM600_GT2_2004", WeightKg = 1150, Year = 2004 },
        new() { ClassString = "class_gt", DescriptionKey = "cardesc_maseratimc12", EngineName = "6.0L V12", FuelCapacityLitres = 75.51000213623047, IconFileName = "Maserati", Id = "ID_Maserati_MC12_GT1", Layout = "Mid Engine - RWD", Manufacturer = "Maserati", Name = "MC12 GT1", PowerBhp = 580, Region = "Europe", TorqueNm = 600, Transmission = "6-Speed Sequential", VehicleClass = "GT", VehiclePath = "Maserati_MC12_GT1", WeightKg = 1100, Year = 2004 },
        new() { ClassString = "class_grc", DescriptionKey = "cardesc_mazda787b", EngineName = "2.6L 4-Rotor", FuelCapacityLitres = 100, IconFileName = "Mazda", Id = "ID_Mazda_787B_1991", Layout = "Mid Engine - RWD", Manufacturer = "Mazda", Name = "787B", PowerBhp = 700, Region = "AsiaAndAus", TorqueNm = 608, Transmission = "5-Speed Manual", VehicleClass = "Group C", VehiclePath = "Mazda_787B_1991", WeightKg = 830, Year = 1991 },
        new() { ClassString = "class_MX5 Trophy", DescriptionKey = "cardesc_mazdamx5", EngineName = "2.0L L4", FuelCapacityLitres = 34, IconFileName = "Mazda", Id = "ID_Mazda_MX-5_Cup_2017", Layout = "Front Engine - RWD", Manufacturer = "Mazda", Name = "MX-5 Spec", PowerBhp = 170, Region = "Americas", TorqueNm = 204, Transmission = "6-Speed Manual", VehicleClass = "MX5 Trophy", VehiclePath = "Mazda_MX-5_Cup_2017", WeightKg = 1095, Year = 2017 },
        new() { ClassString = "class_gto", DescriptionKey = "cardesc_mazdarx7gto", EngineName = "2.6L 4-Rotor", FuelCapacityLitres = 75.51000213623047, IconFileName = "Mazda", Id = "ID_MAZDA_RX-7_GTO_1989", Layout = "Front Engine - RWD", Manufacturer = "Mazda", Name = "RX-7 GTO", PowerBhp = 600, Region = "Americas", TorqueNm = 530, Transmission = "5-Speed Manual", VehicleClass = "GTO", VehiclePath = "MAZDA_RX-7_GTO_1989", WeightKg = 1020, Year = 1989 },
        new() { ClassString = "class_GT3", DescriptionKey = "cardesc_mercedesgt3", EngineName = "6.3L V8", FuelCapacityLitres = 90.5999984741211, IconFileName = "Mercedes", Id = "ID_Mercedes_AMG_GT3_Evo", Layout = "Front Engine - RWD", Manufacturer = "Mercedes-AMG", Name = "GT3", PowerBhp = 520, Region = "Europe", TorqueNm = 625, Transmission = "6-Speed Paddle", VehicleClass = "GT3", VehiclePath = "Mercedes_AMG_GT3_Evo_2020", WeightKg = 1325, Year = 2020 },
        new() { ClassString = "class_gt4", DescriptionKey = "cardesc_mercedesgt4", EngineName = "4.0L V8 Twin Turbo", FuelCapacityLitres = 120, IconFileName = "Mercedes", Id = "ID_Mercedes_AMG_GT4", Layout = "Front Engine - RWD", Manufacturer = "Mercedes-AMG", Name = "GT4", PowerBhp = 470, Region = "Europe", TorqueNm = 580, Transmission = "6-Speed Paddle", VehicleClass = "GT4", VehiclePath = "Mercedes_AMG_GT4", WeightKg = 1390, Year = 2020 },
        new() { ClassString = "class_gt1", DescriptionKey = "cardesc_mercedesclk", EngineName = "5.0L V8", FuelCapacityLitres = 100, IconFileName = "Mercedes", Id = "ID_Mercedes_CLK-LM_1998", Layout = "Mid Engine - RWD", Manufacturer = "Mercedes-Benz", Name = "CLK-LM", PowerBhp = 600, Region = "Europe", TorqueNm = 685, Transmission = "6-Speed Sequential", VehicleClass = "GT1", VehiclePath = "Mercedes_CLK-LM_1998", WeightKg = 971, Year = 1998 },
        new() { ClassString = "class_grc", DescriptionKey = "cardesc_sauberc9", EngineName = "5.0L V8 Twin Turbo", FuelCapacityLitres = 100, IconFileName = "Mercedes", Id = "ID_Sauber_C9_1989", Layout = "Mid Engine - RWD", Manufacturer = "Mercedes-Benz", Name = "Sauber C9", PowerBhp = 820, Region = "Europe", TorqueNm = 922, Transmission = "5-Speed Manual", VehicleClass = "Group C", VehiclePath = "Sauber_C9_1989", WeightKg = 905, Year = 1989 },
        new() { ClassString = "class_GTO", DescriptionKey = "cardesc_mercurycougar", EngineName = "5.5L V8", FuelCapacityLitres = 75.51000213623047, IconFileName = "Mercury", Id = "ID_Mercury_Cougar_XR-7_GTO_1989", Layout = "Front Engine - RWD", Manufacturer = "Mercury", Name = "Cougar XR-7 GTO", PowerBhp = 675, Region = "Americas", TorqueNm = 660, Transmission = "5-Speed Manual", VehicleClass = "GTO", VehiclePath = "Mercury_Cougar_XR-7_GTO_1989", WeightKg = 1175, Year = 1989 },
        new() { ClassString = "class_n-gt", DescriptionKey = "cardesc_morganaero8", EngineName = "4.6L V8", FuelCapacityLitres = 75.51000213623047, IconFileName = "Morgan", Id = "ID_Morgan_Aero_8_GTN", Layout = "Front Engine - RWD", Manufacturer = "Morgan", Name = "Aero 8 GT(N)", PowerBhp = 410, Region = "Europe", TorqueNm = 500, Transmission = "6-Speed Sequential", VehicleClass = "N-GT", VehiclePath = "Morgan_Aero_8_GTN", WeightKg = 1010, Year = 2004 },
        new() { ClassString = "class_n-gt", DescriptionKey = "cardesc_moslermt900r", EngineName = "5.7L V8", FuelCapacityLitres = 90, IconFileName = "Mosler", Id = "ID_Mosler_MT900R", Layout = "Mid Engine - RWD", Manufacturer = "Mosler", Name = "MT900R", PowerBhp = 450, Region = "Americas", TorqueNm = 425, Transmission = "6-Speed Sequential", VehicleClass = "N-GT", VehiclePath = "Mosler_MT900R_2004", WeightKg = 1100, Year = 2004 },
        new() { ClassString = "class_GTO", DescriptionKey = "cardesc_nissan300zx", EngineName = "3.0L V6 Turbo", FuelCapacityLitres = 75.51000213623047, IconFileName = "Nissan", Id = "ID_Nissan_300ZX_IMSA_GTO_1989", Layout = "Front Engine - RWD", Manufacturer = "Nissan", Name = "300ZX Turbo GTO", PowerBhp = 750, Region = "Americas", TorqueNm = 850, Transmission = "5-Speed Manual", VehicleClass = "GTO", VehiclePath = "Nissan_300ZX_IMSA_GTO_1989", WeightKg = 1225, Year = 1989 },
        new() { ClassString = "class_gt1", DescriptionKey = "cardesc_nissanr390", EngineName = "3.5L V8 Twin Turbo", FuelCapacityLitres = 100, IconFileName = "Nissan", Id = "ID_Nissan_R390_GT1", Layout = "Mid Engine - RWD", Manufacturer = "Nissan", Name = "R390 GT1", PowerBhp = 642, Region = "AsiaAndAus", TorqueNm = 706, Transmission = "6-Speed Sequential", VehicleClass = "GT1", VehiclePath = "Nissan_R390_GT1", WeightKg = 1000, Year = 1998 },
        new() { ClassString = "class_grc", DescriptionKey = "cardesc_nissanr89c", EngineName = "3.5L V8 Twin Turbo", FuelCapacityLitres = 100, IconFileName = "Nissan", Id = "ID_Nissan_R89C", Layout = "Mid Engine - RWD", Manufacturer = "Nissan", Name = "R89C", PowerBhp = 789, Region = "AsiaAndAus", TorqueNm = 784, Transmission = "5-Speed Manual", VehicleClass = "Group C", VehiclePath = "Nissan_R89C", WeightKg = 900, Year = 1989 },
        new() { ClassString = "class_gt4", DescriptionKey = "cardesc_nissanzgt4", EngineName = "3.0L V6 Twin Turbo", FuelCapacityLitres = 120, IconFileName = "Nissan", Id = "ID_Nissan_Z_GT4_2023", Layout = "Front Engine - RWD", Manufacturer = "Nissan", Name = "Z GT4", PowerBhp = 440, Region = "AsiaAndAus", TorqueNm = 600, Transmission = "6-Speed Paddle", VehicleClass = "GT4", VehiclePath = "Nissan_Z_GT4_2023", WeightKg = 1460, Year = 2023 },
        new() { ClassString = "class_gt1", DescriptionKey = "cardesc_panozesperante", EngineName = "6.0L V8", FuelCapacityLitres = 100, IconFileName = "Panoz", Id = "ID_PANOZ_ESPERANTE_GTR1", Layout = "Front Engine - RWD", Manufacturer = "Panoz", Name = "Esperante GTR-1", PowerBhp = 610, Region = "Americas", TorqueNm = 670, Transmission = "6-Speed Sequential", VehicleClass = "GT1", VehiclePath = "Panoz_Esperante_GTR1", WeightKg = 960, Year = 1998 },
        new() { ClassString = "class_LMP", DescriptionKey = "cardesc_panozlmp1", EngineName = "6.0L V8", FuelCapacityLitres = 90, IconFileName = "Panoz", Id = "ID_Panoz_LMP1_Roadster_S_99", Layout = "Front Engine - RWD", Manufacturer = "Panoz", Name = "LMP1 Roadster S", PowerBhp = 630, Region = "Americas", TorqueNm = 670, Transmission = "6-Speed Sequential", VehicleClass = "LMP", VehiclePath = "Panoz_LMP1_Roadster_S_99", WeightKg = 905, Year = 1999 },
        new() { ClassString = "class_LMDh", DescriptionKey = "cardesc_peugeot9x8", EngineName = "2.6L V6 Twin Turbo", FuelCapacityLitres = null, IconFileName = "Peugeot", Id = "ID_Peugeot_9X8_2024", Layout = "Mid Engine - RWD", Manufacturer = "Peugeot", Name = "9X8", PowerBhp = 670, Region = "Europe", TorqueNm = 670, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", VehiclePath = "Peugeot_9X8_2024", WeightKg = 1030, Year = 2024 },
        new() { ClassString = "class_gt4", DescriptionKey = "cardesc_porschecayman", EngineName = "4.0L Flat-6", FuelCapacityLitres = 115, IconFileName = "Porsche", Id = "ID_Porsche_Cayman_GT4_Clubsport_2022", Layout = "Mid Engine - RWD", Manufacturer = "Porsche", Name = "718 Cayman GT4 Clubsport", PowerBhp = 430, Region = "Europe", TorqueNm = 420, Transmission = "7-Speed Paddle", VehicleClass = "GT4", VehiclePath = "Porsche_Cayman_GT4_Clubsport_2022", WeightKg = 1420, Year = 2020 },
        new() { ClassString = "class_cc90", DescriptionKey = "cardesc_porsche964", EngineName = "3.6L Flat-6", FuelCapacityLitres = 100, IconFileName = "Porsche", Id = "ID_Porsche_Carrera_Cup", Layout = "Rear Engine - RWD", Manufacturer = "Porsche", Name = "911 Carrera Cup (964)", PowerBhp = 261, Region = "Europe", TorqueNm = 310, Transmission = "5-Speed Manual", VehicleClass = "964 Trophy", VehiclePath = "Porsche_Carrera_Cup", WeightKg = 1120, Year = 1990 },
        new() { ClassString = "class_gt1", DescriptionKey = "cardesc_porsche911gt1", EngineName = "3.2L Flat-6 Turbo", FuelCapacityLitres = 100, IconFileName = "Porsche", Id = "ID_Porsche_911_GT1_98", Layout = "Mid Engine - RWD", Manufacturer = "Porsche", Name = "911 GT1-98", PowerBhp = 580, Region = "Europe", TorqueNm = 630, Transmission = "6-Speed Sequential", VehicleClass = "GT1", VehiclePath = "Porsche_911_GT1_98", WeightKg = 967, Year = 1998 },
        new() { ClassString = "class_cc24", DescriptionKey = "cardesc_porsche992cup", EngineName = "4.0L Flat-6", FuelCapacityLitres = 75.51000213623047, IconFileName = "Porsche", Id = "ID_Porsche_911_GT3_Cup_2022", Layout = "Rear Engine - RWD", Manufacturer = "Porsche", Name = "911 GT3 Cup (992)", PowerBhp = 503, Region = "Europe", TorqueNm = 470, Transmission = "6-Speed Paddle", VehicleClass = "992 Trophy", VehiclePath = "Porsche_911_GT3_Cup_2022", WeightKg = 1260, Year = 2024 },
        new() { ClassString = "class_gt3", DescriptionKey = "cardesc_porsche992gt3r", EngineName = "4.2L Flat-6", FuelCapacityLitres = 90.5999984741211, IconFileName = "Porsche", Id = "ID_Porsche_992_GT3R", Layout = "Rear Engine - RWD", Manufacturer = "Porsche", Name = "911 GT3 R (992)", PowerBhp = 565, Region = "Europe", TorqueNm = 560, Transmission = "6-Speed Paddle", VehicleClass = "GT3", VehiclePath = "Porsche_992_GT3R", WeightKg = 1325, Year = 2023 },
        new() { ClassString = "class_n-gt", DescriptionKey = "cardesc_porsche996rsr", EngineName = "3.6L Flat-6", FuelCapacityLitres = 67.5, IconFileName = "Porsche", Id = "ID_Porsche_911_GT3-RSR_2004", Layout = "Rear Engine - RWD", Manufacturer = "Porsche", Name = "911 GT3-RSR (996)", PowerBhp = 450, Region = "Europe", TorqueNm = 405, Transmission = "6-Speed Sequential", VehicleClass = "N-GT", VehiclePath = "Porsche_911_GT3-RSR_2004", WeightKg = 1125, Year = 2004 },
        new() { ClassString = "class_Sports Car 70", DescriptionKey = "cardesc_porsche917k", EngineName = "4.5L Flat-12", FuelCapacityLitres = 120, IconFileName = "Porsche", Id = "ID_Porsche_917K_1970", Layout = "Mid Engine - RWD", Manufacturer = "Porsche", Name = "917K", PowerBhp = 520, Region = "Europe", TorqueNm = 490, Transmission = "5-Speed Manual", VehicleClass = "Sports Car 70", VehiclePath = "Porsche_917K_1970", WeightKg = 840, Year = 1970 },
        new() { ClassString = "class_grc", DescriptionKey = "cardesc_porsche962c", EngineName = "2.8L Flat-6 Turbo", FuelCapacityLitres = 100, IconFileName = "Porsche", Id = "ID_Porsche_962C_88", Layout = "Mid Engine - RWD", Manufacturer = "Porsche", Name = "962C", PowerBhp = 780, Region = "Europe", TorqueNm = 710, Transmission = "5-Speed Manual", VehicleClass = "Group C", VehiclePath = "Porsche_962C_88", WeightKg = 871, Year = 1988 },
        new() { ClassString = "class_LMDh", DescriptionKey = "cardesc_porsche963", EngineName = "4.6L V8 Twin Turbo", FuelCapacityLitres = null, IconFileName = "Porsche", Id = "ID_Porsche_963", Layout = "Mid Engine - RWD", Manufacturer = "Porsche", Name = "963", PowerBhp = 670, Region = "Europe", TorqueNm = 710, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", VehiclePath = "Porsche_963", WeightKg = 1030, Year = 2023 },
        new() { ClassString = "class_gt", DescriptionKey = "cardesc_saleens7r", EngineName = "7.0L V8", FuelCapacityLitres = 75.51000213623047, IconFileName = "Saleen", Id = "ID_Saleen_S7R", Layout = "Mid Engine - RWD", Manufacturer = "Saleen", Name = "S7R", PowerBhp = 600, Region = "Americas", TorqueNm = 746, Transmission = "6-Speed Sequential", VehicleClass = "GT", VehiclePath = "Saleen_S7R", WeightKg = 1150, Year = 2004 },
        new() { ClassString = "class_gt4", DescriptionKey = "cardesc_toyotasupra", EngineName = "3.0L L6 Twin Turbo", FuelCapacityLitres = 120, IconFileName = "Toyota", Id = "ID_Toyota_Supra_GT4", Layout = "Front Engine - RWD", Manufacturer = "Toyota", Name = "GR Supra GT4 EVO", PowerBhp = 430, Region = "Europe", TorqueNm = 585, Transmission = "6-Speed Paddle", VehicleClass = "GT4", VehiclePath = "Toyota_Supra_GT4", WeightKg = 1370, Year = 2023 },
        new() { ClassString = "class_LMDh", DescriptionKey = "cardesc_toyotagr010", EngineName = "3.5L V6 Twin Turbo", FuelCapacityLitres = null, IconFileName = "Toyota", Id = "ID_Toyota_GR010", Layout = "Mid Engine - RWD", Manufacturer = "Toyota", Name = "GR010 Hybrid", PowerBhp = 670, Region = "Europe", TorqueNm = 740, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", VehiclePath = "Toyota_GR010", WeightKg = 1030, Year = 2023 },
        new() { ClassString = "class_gt1", DescriptionKey = "cardesc_toyotagtone", EngineName = "3.6L V8 Twin Turbo", FuelCapacityLitres = 100, IconFileName = "Toyota", Id = "ID_Toyota_GT-One_TS020", Layout = "Mid Engine - RWD", Manufacturer = "Toyota", Name = "GT-One", PowerBhp = 600, Region = "Europe", TorqueNm = 650, Transmission = "6-Speed Sequential", VehicleClass = "GT1", VehiclePath = "Toyota_GT-One_TS020", WeightKg = 921, Year = 1998 },
        new() { ClassString = "class_n-gt", DescriptionKey = "cardesc_tvrtuscan", EngineName = "4.0L L6", FuelCapacityLitres = 67.5, IconFileName = "TVR", Id = "ID_TVR_TUSCAN_T400R_2002", Layout = "Front Engine - RWD", Manufacturer = "TVR", Name = "Tuscan T400R", PowerBhp = 390, Region = "Europe", TorqueNm = 420, Transmission = "6-Speed Sequential", VehicleClass = "N-GT", VehiclePath = "TVR_TUSCAN_T400R_2002", WeightKg = 1100, Year = 2004 },
    ];

    public static PmrCarInfoProvider Instance => singletonInstance ??= new PmrCarInfoProvider();

    public PmrCarInfo? FindById(string id)
    {
        return this.cars.FirstOrDefault(c => c.Id == id);
    }

    public PmrCarInfo? FindByVehiclePath(string vehiclePath)
    {
        return this.cars.FirstOrDefault(c => c.VehiclePath == vehiclePath);
    }

    public IReadOnlyCollection<PmrCarInfo> GetCarInfos()
    {
        return this.cars.AsReadOnly();
    }

    public IReadOnlyCollection<PmrCarInfo> GetCarInfosForManufacturer(string manufacturer)
    {
        return this.cars.Where(c => c.Manufacturer == manufacturer)
                         .ToList()
                         .AsReadOnly();
    }

    public IReadOnlyCollection<string> GetManufacturers()
    {
        return this.cars.Select(c => c.Manufacturer)
                         .Distinct()
                         .OrderBy(m => m)
                         .ToList()
                         .AsReadOnly();
    }
}
