using SimRacingSdk.Pmr.Core.Abstractions;
using SimRacingSdk.Pmr.Core.Models;

namespace SimRacingSdk.Pmr.Core;

public class PmrCarInfoProvider : IPmrCarInfoProvider
{
    private static PmrCarInfoProvider? singletonInstance;

    private readonly List<PmrCarInfo> cars =
    [
        new() { EngineDisplacementLitres = 2.4, EngineLayout = "Mid Engine", EngineType = "V6 Twin Turbo", FuelCapacityLitres = null, GameId = "ID_Acura_ARX-06_2023", IconFileName = "Acura", Id = "Acura_ARX-06_2023", Manufacturer = "Acura", Name = "ARX-06", PowerKw = 499, PowertrainLayout = "RWD", TorqueNm = 688, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", WeightKg = 1030, Year = 2023 },
        new() { EngineDisplacementLitres = 3.5, EngineLayout = "Mid Engine", EngineType = "V6 Twin Turbo", FuelCapacityLitres = 90.6, GameId = "ID_HONDA_NSX_GT3", IconFileName = "Acura", Id = "Acura_NSX_GT3_Evo_22_2022", Manufacturer = "Acura", Name = "NSX GT3 Evo 22", PowerKw = 387, PowertrainLayout = "RWD", TorqueNm = 640, Transmission = "6-Speed Paddle", VehicleClass = "GT3", WeightKg = 1290, Year = 2022 },
        new() { EngineDisplacementLitres = 1.8, EngineLayout = "Mid Engine", EngineType = "L4 Turbo", FuelCapacityLitres = 95, GameId = "ID_Alpine_A110_GT4_2020", IconFileName = "Alpine", Id = "Alpine_A110_GT4_2020", Manufacturer = "Alpine", Name = "A110 GT4", PowerKw = 268, PowertrainLayout = "RWD", TorqueNm = 488, Transmission = "6-Speed Paddle", VehicleClass = "GT4", WeightKg = 1160, Year = 2020 },
        new() { EngineDisplacementLitres = 3.4, EngineLayout = "Mid Engine", EngineType = "V6 Twin Turbo", FuelCapacityLitres = null, GameId = "ID_Alpine_A424_2024", IconFileName = "Alpine", Id = "Alpine_A424_Beta_2024", Manufacturer = "Alpine", Name = "A424 Beta", PowerKw = 499, PowertrainLayout = "RWD", TorqueNm = 670, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", WeightKg = 1030, Year = 2024 },
        new() { EngineDisplacementLitres = 5, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_AMC_Javelin_Trans_Am_1971", IconFileName = "AMC", Id = "AMC_Javelin_1971", Manufacturer = "AMC", Name = "Javelin", PowerKw = 335, PowertrainLayout = "RWD", TorqueNm = 500, Transmission = "4-Speed Manual", VehicleClass = "Historic USV8", WeightKg = 1407, Year = 1971 },
        new() { EngineDisplacementLitres = 4, EngineLayout = "Front Engine", EngineType = "V8 Twin Turbo", FuelCapacityLitres = 90.6, GameId = "ID_Aston_Martin_Vantage_GT3_Evo", IconFileName = "Aston Martin", Id = "Aston_Martin_AMR_Vantage_GT3_2024", Manufacturer = "Aston Martin", Name = "AMR Vantage GT3", PowerKw = 378, PowertrainLayout = "RWD", TorqueNm = 690, Transmission = "6-Speed Paddle", VehicleClass = "GT3", WeightKg = 1325, Year = 2024 },
        new() { EngineDisplacementLitres = 4, EngineLayout = "Front Engine", EngineType = "V8 Twin Turbo", FuelCapacityLitres = 90.6, GameId = "ID_Aston_Martin_Vantage_GT3", IconFileName = "Aston Martin", Id = "Aston_Martin_AMR_Vantage_GT3_2022_2022", Manufacturer = "Aston Martin", Name = "AMR Vantage GT3 2022", PowerKw = 378, PowertrainLayout = "RWD", TorqueNm = 690, Transmission = "6-Speed Paddle", VehicleClass = "GT3", WeightKg = 1325, Year = 2022 },
        new() { EngineDisplacementLitres = 4, EngineLayout = "Front Engine", EngineType = "V8 Twin Turbo", FuelCapacityLitres = 120, GameId = "ID_Aston_Martin_Vantage_AMR_GT4", IconFileName = "Aston Martin", Id = "Aston_Martin_AMR_Vantage_GT4_2020", Manufacturer = "Aston Martin", Name = "AMR Vantage GT4", PowerKw = 354, PowertrainLayout = "RWD", TorqueNm = 690, Transmission = "6-Speed Paddle", VehicleClass = "GT4", WeightKg = 1400, Year = 2020 },
        new() { EngineDisplacementLitres = 4, EngineLayout = "Front Engine", EngineType = "V8 Twin Turbo", FuelCapacityLitres = null, GameId = "ID_Aston_Martin_Vantage_GTE_2020", IconFileName = "Aston Martin", Id = "Aston_Martin_AMR_Vantage_Gte_2020", Manufacturer = "Aston Martin", Name = "AMR Vantage Gte", PowerKw = 399, PowertrainLayout = "RWD", TorqueNm = 700, Transmission = "6-Speed Paddle", VehicleClass = "GTE", WeightKg = 1245, Year = 2020 },
        new() { EngineDisplacementLitres = 6, EngineLayout = "Front Engine", EngineType = "V12", FuelCapacityLitres = 75.5, GameId = "ID_Aston_Martin_DBR9_2005", IconFileName = "Aston Martin", Id = "Aston_Martin_DBR9_2005", Manufacturer = "Aston Martin", Name = "DBR9", PowerKw = 466, PowertrainLayout = "RWD", TorqueNm = 700, Transmission = "6-Speed Sequential", VehicleClass = "GT", WeightKg = 1170, Year = 2005 },
        new() { EngineDisplacementLitres = 6.5, EngineLayout = "Mid Engine", EngineType = "V12", FuelCapacityLitres = 110, GameId = "ID_Aston_Martin_Valkyrie_LMH_2025", IconFileName = "Aston Martin", Id = "Aston_Martin_Valkyrie_Hypercar_2025", Manufacturer = "Aston Martin", Name = "Valkyrie Hypercar", PowerKw = 507, PowertrainLayout = "RWD", TorqueNm = 750, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", WeightKg = 1030, Year = 2025 },
        new() { EngineDisplacementLitres = 2.2, EngineLayout = "Front Engine", EngineType = "L5 Turbo", FuelCapacityLitres = 75.5, GameId = "ID_Audi_90_IMSA_GTO_1989", IconFileName = "Audi", Id = "Audi_90_IMSA_GTO_1989", Manufacturer = "Audi", Name = "90 IMSA GTO", PowerKw = 529, PowertrainLayout = "4WD", TorqueNm = 720, Transmission = "5-Speed Manual", VehicleClass = "GTO", WeightKg = 1207, Year = 1989 },
        new() { EngineDisplacementLitres = 3.6, EngineLayout = "Mid Engine", EngineType = "V8 Twin Turbo", FuelCapacityLitres = 90, GameId = "ID_Audi_R8_LMP900_2002", IconFileName = "Audi", Id = "Audi_R8_(LMP900)_2002", Manufacturer = "Audi", Name = "R8 (LMP900)", PowerKw = 473, PowertrainLayout = "RWD", TorqueNm = 680, Transmission = "6-Speed Paddle", VehicleClass = "LMP", WeightKg = 911, Year = 2002 },
        new() { EngineDisplacementLitres = 5.2, EngineLayout = "Mid Engine", EngineType = "V10", FuelCapacityLitres = 90.6, GameId = "ID_Audi_R8_LMS_GT3_Evo", IconFileName = "Audi", Id = "Audi_R8_GT3_Evo_II_2022", Manufacturer = "Audi", Name = "R8 GT3 Evo II", PowerKw = 384, PowertrainLayout = "RWD", TorqueNm = 580, Transmission = "6-Speed Paddle", VehicleClass = "GT3", WeightKg = 1310, Year = 2022 },
        new() { EngineDisplacementLitres = 5.2, EngineLayout = "Mid Engine", EngineType = "V10", FuelCapacityLitres = 113, GameId = "ID_Audi_R8_LMS_GT4_Evo", IconFileName = "Audi", Id = "Audi_R8_LMS_GT4_Evo_2020", Manufacturer = "Audi", Name = "R8 LMS GT4 Evo", PowerKw = 328, PowertrainLayout = "RWD", TorqueNm = 480, Transmission = "7-Speed Paddle", VehicleClass = "GT4", WeightKg = 1485, Year = 2020 },
        new() { EngineDisplacementLitres = 2, EngineLayout = "Front Engine", EngineType = "L4 Turbo", FuelCapacityLitres = null, GameId = "ID_BMW_320_Turbo_Group5", IconFileName = "BMW", Id = "BMW_320_Turbo_Group_5_1978", Manufacturer = "BMW", Name = "320 Turbo Group 5", PowerKw = 447, PowertrainLayout = "RWD", TorqueNm = 515, Transmission = "5-Speed Manual", VehicleClass = "Group 5", WeightKg = 880, Year = 1978 },
        new() { EngineDisplacementLitres = 4, EngineLayout = "Mid Engine", EngineType = "V8 Twin Turbo", FuelCapacityLitres = null, GameId = "ID_BMW_M_Hybrid_V8", IconFileName = "BMW", Id = "BMW_M_Hybrid_V8_2023", Manufacturer = "BMW", Name = "M Hybrid V8", PowerKw = 499, PowertrainLayout = "RWD", TorqueNm = 700, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", WeightKg = 1030, Year = 2023 },
        new() { EngineDisplacementLitres = 4, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = 67.5, GameId = "ID_BMW_M3_E46", IconFileName = "BMW", Id = "BMW_M3_GTR_(E46)_2004", Manufacturer = "BMW", Name = "M3 GTR (E46)", PowerKw = 335, PowertrainLayout = "RWD", TorqueNm = 365, Transmission = "6-Speed Sequential", VehicleClass = "N-GT", WeightKg = 1120, Year = 2004 },
        new() { EngineDisplacementLitres = 3, EngineLayout = "Front Engine", EngineType = "L6 Twin Turbo", FuelCapacityLitres = 90.6, GameId = "ID_BMW_M4_GT3", IconFileName = "BMW", Id = "BMW_M4_GT3_EVO_2025", Manufacturer = "BMW", Name = "M4 GT3 EVO", PowerKw = 391, PowertrainLayout = "RWD", TorqueNm = 650, Transmission = "6-Speed Paddle", VehicleClass = "GT3", WeightKg = 1360, Year = 2025 },
        new() { EngineDisplacementLitres = 3, EngineLayout = "Front Engine", EngineType = "L6 Twin Turbo", FuelCapacityLitres = 120, GameId = "ID_BMW_M4_GT4", IconFileName = "BMW", Id = "BMW_M4_GT4_EVO_2025", Manufacturer = "BMW", Name = "M4 GT4 EVO", PowerKw = 386, PowertrainLayout = "RWD", TorqueNm = 550, Transmission = "7-Speed Paddle", VehicleClass = "GT4", WeightKg = 1430, Year = 2025 },
        new() { EngineDisplacementLitres = 4, EngineLayout = "Front Engine", EngineType = "V8 Twin Turbo", FuelCapacityLitres = null, GameId = "ID_BMW_M8_GTE", IconFileName = "BMW", Id = "BMW_M8_GTE_2020", Manufacturer = "BMW", Name = "M8 GTE", PowerKw = 447, PowertrainLayout = "RWD", TorqueNm = 700, Transmission = "6-Speed Paddle", VehicleClass = "GTE", WeightKg = 1170, Year = 2020 },
        new() { EngineDisplacementLitres = 6, EngineLayout = "Mid Engine", EngineType = "V12", FuelCapacityLitres = 90, GameId = "ID_BMW_V12_LMR", IconFileName = "BMW", Id = "BMW_V12_LMR_1999", Manufacturer = "BMW", Name = "V12 LMR", PowerKw = 439, PowertrainLayout = "RWD", TorqueNm = 678, Transmission = "6-Speed Sequential", VehicleClass = "LMP", WeightKg = 914, Year = 1999 },
        new() { EngineDisplacementLitres = 4, EngineLayout = "Mid Engine", EngineType = "V8 Twin Turbo", FuelCapacityLitres = 75.5, GameId = "ID_Cadillac_Northstar_LMP900", IconFileName = "Cadillac", Id = "Cadillac_Northstar_LMP-02_2002", Manufacturer = "Cadillac", Name = "Northstar LMP-02", PowerKw = 462, PowertrainLayout = "RWD", TorqueNm = 700, Transmission = "6-Speed Paddle", VehicleClass = "LMP", WeightKg = 916, Year = 2002 },
        new() { EngineDisplacementLitres = 5.5, EngineLayout = "Mid Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Cadillac_V_SeriesR", IconFileName = "Cadillac", Id = "Cadillac_V-Series.R_2023", Manufacturer = "Cadillac", Name = "V-Series.R", PowerKw = 499, PowertrainLayout = "RWD", TorqueNm = 740, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", WeightKg = 1030, Year = 2023 },
        new() { EngineDisplacementLitres = 7, EngineLayout = "Mid Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Chaparral_2F_1967", IconFileName = "Chaparral", Id = "Chaparral_2F_1967", Manufacturer = "Chaparral", Name = "2F", PowerKw = 391, PowertrainLayout = "RWD", TorqueNm = 630, Transmission = "3-Speed Automatic", VehicleClass = "Sports Car 67", WeightKg = 795, Year = 1967 },
        new() { EngineDisplacementLitres = 6.2, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_TA2_Chevrolet_Camaro_2024", IconFileName = "Chevrolet", Id = "Chevrolet_Camaro_2024", Manufacturer = "Chevrolet", Name = "Camaro", PowerKw = 387, PowertrainLayout = "RWD", TorqueNm = 657, Transmission = "4-Speed Manual", VehicleClass = "USV8", WeightKg = 1204, Year = 2024 },
        new() { EngineDisplacementLitres = 5, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Chevrolet_Camaro_Z28_Trans_Am_1969", IconFileName = "Chevrolet", Id = "Chevrolet_Camaro_1969", Manufacturer = "Chevrolet", Name = "Camaro", PowerKw = 328, PowertrainLayout = "RWD", TorqueNm = 430, Transmission = "4-Speed Manual", VehicleClass = "Historic USV8", WeightKg = 1404, Year = 1969 },
        new() { EngineDisplacementLitres = 5.7, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Chevrolet_Camaro_V8Supercar_2024", IconFileName = "Chevrolet", Id = "Chevrolet_Camaro_AU_2023", Manufacturer = "Chevrolet", Name = "Camaro AU", PowerKw = 447, PowertrainLayout = "RWD", TorqueNm = 660, Transmission = "6-Speed Sequential", VehicleClass = "AUS V8 Evo", WeightKg = 1260, Year = 2023 },
        new() { EngineDisplacementLitres = 6, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = 75.5, GameId = "ID_Chevrolet_Camaro_Z28_GTO_1989", IconFileName = "Chevrolet", Id = "Chevrolet_Camaro_Z28_GTO_1989", Manufacturer = "Chevrolet", Name = "Camaro Z28 GTO", PowerKw = 447, PowertrainLayout = "RWD", TorqueNm = 666, Transmission = "5-Speed Manual", VehicleClass = "GTO", WeightKg = 1225, Year = 1989 },
        new() { EngineDisplacementLitres = 6.2, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = 87, GameId = "ID_Chevrolet_Camaro_ZL-1_GT4_2017", IconFileName = "Chevrolet", Id = "Chevrolet_Camaro_ZL-1_GT4.R_2007", Manufacturer = "Chevrolet", Name = "Camaro ZL-1 GT4.R", PowerKw = 328, PowertrainLayout = "RWD", TorqueNm = 575, Transmission = "6-Speed Paddle", VehicleClass = "GT4", WeightKg = 1470, Year = 2007 },
        new() { EngineDisplacementLitres = 6.2, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Chevrolet_Corvette_Grand_Sport", IconFileName = "Chevrolet", Id = "Chevrolet_Corevette_Grand_Sport_1963", Manufacturer = "Chevrolet", Name = "Corevette Grand Sport", PowerKw = 361, PowertrainLayout = "RWD", TorqueNm = 607, Transmission = "4-Speed Manual", VehicleClass = "GT 60", WeightKg = 985, Year = 1963 },
        new() { EngineDisplacementLitres = 7, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Chevrolet_Corvette_C3_1973", IconFileName = "Chevrolet", Id = "Chevrolet_Corvette_C3_1973", Manufacturer = "Chevrolet", Name = "Corvette C3", PowerKw = 391, PowertrainLayout = "RWD", TorqueNm = 630, Transmission = "4-Speed Manual", VehicleClass = "GT 70", WeightKg = 1275, Year = 1973 },
        new() { EngineDisplacementLitres = 7, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = 75.5, GameId = "ID_Chevrolet_Corvette_C5R", IconFileName = "Chevrolet", Id = "Chevrolet_Corvette_C5.R_2004", Manufacturer = "Chevrolet", Name = "Corvette C5.R", PowerKw = 454, PowertrainLayout = "RWD", TorqueNm = 770, Transmission = "6-Speed Manual", VehicleClass = "GT", WeightKg = 1270, Year = 2004 },
        new() { EngineDisplacementLitres = 7, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = 75.5, GameId = "ID_Chevrolet_Corvette_C6R", IconFileName = "Chevrolet", Id = "Chevrolet_Corvette_C6.R_2005", Manufacturer = "Chevrolet", Name = "Corvette C6.R", PowerKw = 425, PowertrainLayout = "RWD", TorqueNm = 840, Transmission = "6-Speed Sequential", VehicleClass = "GT", WeightKg = 1100, Year = 2005 },
        new() { EngineDisplacementLitres = 5.5, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Chevrolet_Corvette_C7R_GTE", IconFileName = "Chevrolet", Id = "Chevrolet_Corvette_C7.R_2017", Manufacturer = "Chevrolet", Name = "Corvette C7.R", PowerKw = 365, PowertrainLayout = "RWD", TorqueNm = 660, Transmission = "6-Speed Paddle", VehicleClass = "GTE", WeightKg = 1110, Year = 2017 },
        new() { EngineDisplacementLitres = 5.5, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Chevrolet_Corvette_C8R_GTE_2020", IconFileName = "Chevrolet", Id = "Chevrolet_Corvette_C8.R_2020", Manufacturer = "Chevrolet", Name = "Corvette C8.R", PowerKw = 372, PowertrainLayout = "RWD", TorqueNm = 650, Transmission = "6-Speed Paddle", VehicleClass = "GTE", WeightKg = 1170, Year = 2020 },
        new() { EngineDisplacementLitres = 5.5, EngineLayout = "Mid Engine", EngineType = "V8", FuelCapacityLitres = 90.6, GameId = "ID_Chevrolet_Corvette_Z06_GT3_2024", IconFileName = "Chevrolet", Id = "Chevrolet_Corvette_Z06_GT3.R_2023", Manufacturer = "Chevrolet", Name = "Corvette Z06 GT3.R", PowerKw = 395, PowertrainLayout = "RWD", TorqueNm = 630, Transmission = "6-Speed Paddle", VehicleClass = "GT3", WeightKg = 1345, Year = 2023 },
        new() { EngineDisplacementLitres = 8, EngineLayout = "Front Engine", EngineType = "V10", FuelCapacityLitres = 75.5, GameId = "ID_Chrysler_Viper_GTS-R", IconFileName = "Chrysler", Id = "Chrysler_Viper_GTS-R_2003", Manufacturer = "Chrysler", Name = "Viper GTS-R", PowerKw = 462, PowertrainLayout = "RWD", TorqueNm = 780, Transmission = "6-Speed Manual", VehicleClass = "GT", WeightKg = 1100, Year = 2003 },
        new() { EngineDisplacementLitres = 6.2, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_TA2_Dodge_Challenger_2024", IconFileName = "Dodge", Id = "Dodge_Challenger_2024", Manufacturer = "Dodge", Name = "Challenger", PowerKw = 387, PowertrainLayout = "RWD", TorqueNm = 657, Transmission = "4-Speed Manual", VehicleClass = "USV8", WeightKg = 1204, Year = 2024 },
        new() { EngineDisplacementLitres = 8.4, EngineLayout = "Front Engine", EngineType = "V10", FuelCapacityLitres = null, GameId = "ID_Dodge_SRT_Viper_GTS-R", IconFileName = "Dodge", Id = "Dodge_SRT_Viper_GTS-R_2014", Manufacturer = "Dodge", Name = "SRT Viper GTS-R", PowerKw = 361, PowertrainLayout = "RWD", TorqueNm = 700, Transmission = "6-Speed Sequential", VehicleClass = "GTE", WeightKg = 1150, Year = 2014 },
        new() { EngineDisplacementLitres = 8, EngineLayout = "Front Engine", EngineType = "V10", FuelCapacityLitres = 67.5, GameId = "ID_Dodge_Viper_CC", IconFileName = "Dodge", Id = "Dodge_Viper_Competition_Coupe_2004", Manufacturer = "Dodge", Name = "Viper Competition Coupe", PowerKw = 387, PowertrainLayout = "RWD", TorqueNm = 730, Transmission = "6-Speed Manual", VehicleClass = "N-GT", WeightKg = 1415, Year = 2004 },
        new() { EngineDisplacementLitres = 1.7, EngineLayout = "Front Engine", EngineType = "L4 Turbo", FuelCapacityLitres = null, GameId = "ID_Ford_Zakspeed_Capri_Group5", IconFileName = "Ford", Id = "Ford_Capri_Group_5_1980", Manufacturer = "Ford", Name = "Capri Group 5", PowerKw = 432, PowertrainLayout = "RWD", TorqueNm = 485, Transmission = "5-Speed Manual", VehicleClass = "Group 5", WeightKg = 880, Year = 1980 },
        new() { EngineDisplacementLitres = 3.4, EngineLayout = "Front Engine", EngineType = "V6", FuelCapacityLitres = null, GameId = "ID_Ford_Capri_RS3100_1973", IconFileName = "Ford", Id = "Ford_Capri_RS3_100_1973", Manufacturer = "Ford", Name = "Capri RS3 100", PowerKw = 328, PowertrainLayout = "RWD", TorqueNm = 380, Transmission = "5-Speed Manual", VehicleClass = "GT 70", WeightKg = 1040, Year = 1973 },
        new() { EngineDisplacementLitres = 5, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Ford_Falcon_FG_V8Supercar_2013", IconFileName = "Ford", Id = "Ford_Falcon_FG_COTF_2013", Manufacturer = "Ford", Name = "Falcon FG COTF", PowerKw = 484, PowertrainLayout = "RWD", TorqueNm = 640, Transmission = "6-Speed Manual", VehicleClass = "AUS V8", WeightKg = 1410, Year = 2013 },
        new() { EngineDisplacementLitres = 7, EngineLayout = "Mid Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Ford_GT40_MkIV_1967", IconFileName = "Ford", Id = "Ford_GT40_Mk.IV_1967", Manufacturer = "Ford", Name = "GT40 Mk.IV", PowerKw = 395, PowertrainLayout = "RWD", TorqueNm = 640, Transmission = "4-Speed Manual", VehicleClass = "Sports Car 67", WeightKg = 1065, Year = 1967 },
        new() { EngineDisplacementLitres = 3.5, EngineLayout = "Mid Engine", EngineType = "V6 Twin Turbo", FuelCapacityLitres = null, GameId = "ID_Ford_GTLM_GTE_2022", IconFileName = "Ford", Id = "Ford_GTLM_GTE_2017", Manufacturer = "Ford", Name = "GTLM GTE", PowerKw = 387, PowertrainLayout = "RWD", TorqueNm = 645, Transmission = "6-Speed Paddle", VehicleClass = "GTE", WeightKg = 1200, Year = 2017 },
        new() { EngineDisplacementLitres = 6.2, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_TA2_Ford_Mustang_2024", IconFileName = "Ford", Id = "Ford_Mustang_2024", Manufacturer = "Ford", Name = "Mustang", PowerKw = 387, PowertrainLayout = "RWD", TorqueNm = 657, Transmission = "4-Speed Manual", VehicleClass = "USV8", WeightKg = 1204, Year = 2024 },
        new() { EngineDisplacementLitres = 5.4, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Ford_Mustang_V8Supercar_2024", IconFileName = "Ford", Id = "Ford_Mustang_AU_2023", Manufacturer = "Ford", Name = "Mustang AU", PowerKw = 447, PowertrainLayout = "RWD", TorqueNm = 650, Transmission = "6-Speed Sequential", VehicleClass = "AUS V8 Evo", WeightKg = 1260, Year = 2023 },
        new() { EngineDisplacementLitres = 5, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Ford_Mustang_Boss_302_Trans_Am_1970", IconFileName = "Ford", Id = "Ford_Mustang_Boss_302_1970", Manufacturer = "Ford", Name = "Mustang Boss 302", PowerKw = 350, PowertrainLayout = "RWD", TorqueNm = 487, Transmission = "4-Speed Manual", VehicleClass = "Historic USV8", WeightKg = 1390, Year = 1970 },
        new() { EngineDisplacementLitres = 5.4, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = 90.6, GameId = "ID_Ford_Mustang_GT3_2023", IconFileName = "Ford", Id = "Ford_Mustang_GT3_2023", Manufacturer = "Ford", Name = "Mustang GT3", PowerKw = 387, PowertrainLayout = "RWD", TorqueNm = 660, Transmission = "6-Speed Paddle", VehicleClass = "GT3", WeightKg = 1300, Year = 2023 },
        new() { EngineDisplacementLitres = 5, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = 100, GameId = "ID_Ford_Mustang_GT4_2024", IconFileName = "Ford", Id = "Ford_Mustang_GT4_2024", Manufacturer = "Ford", Name = "Mustang GT4", PowerKw = 372, PowertrainLayout = "RWD", TorqueNm = 580, Transmission = "6-Speed Paddle", VehicleClass = "GT4", WeightKg = 1390, Year = 2024 },
        new() { EngineDisplacementLitres = 3, EngineLayout = "Front Engine", EngineType = "V6", FuelCapacityLitres = 67.5, GameId = "ID_Gillet_Vertigo", IconFileName = "Gillet", Id = "Gillet_Vertigo_2004", Manufacturer = "Gillet", Name = "Vertigo", PowerKw = 257, PowertrainLayout = "RWD", TorqueNm = 425, Transmission = "6-Speed Sequential", VehicleClass = "N-GT", WeightKg = 806, Year = 2004 },
        new() { EngineDisplacementLitres = 5, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Holden_Commodore_VF_V8Supercar_2013", IconFileName = "Holden", Id = "Holden_Commodore_COTF_2013", Manufacturer = "Holden", Name = "Commodore COTF", PowerKw = 484, PowertrainLayout = "RWD", TorqueNm = 640, Transmission = "6-Speed Sequential", VehicleClass = "AUS V8", WeightKg = 1410, Year = 2013 },
        new() { EngineDisplacementLitres = 2, EngineLayout = "Front Engine", EngineType = "L4 Turbo", FuelCapacityLitres = null, GameId = "ID_Honda_Civic_Type-R_GT500", IconFileName = "Honda", Id = "Honda_Civic_JP1_2024", Manufacturer = "Honda", Name = "Civic JP1", PowerKw = 404, PowertrainLayout = "RWD", TorqueNm = 490, Transmission = "6-Speed Paddle", VehicleClass = "JP1", WeightKg = 1020, Year = 2024 },
        new() { EngineDisplacementLitres = 2, EngineLayout = "Front Engine", EngineType = "L4 Turbo", FuelCapacityLitres = null, GameId = "ID_HONDA_NSX_GT500_2023", IconFileName = "Honda", Id = "Honda_NSX_JP1_2023", Manufacturer = "Honda", Name = "NSX JP1", PowerKw = 404, PowertrainLayout = "RWD", TorqueNm = 490, Transmission = "6-Speed Paddle", VehicleClass = "JP1", WeightKg = 1020, Year = 2023 },
        new() { EngineDisplacementLitres = 3.5, EngineLayout = "Mid Engine", EngineType = "V6", FuelCapacityLitres = null, GameId = "ID_Honda_NSX_JGTC_2003", IconFileName = "Honda", Id = "Honda_NSX_JP2_2003", Manufacturer = "Honda", Name = "NSX JP2", PowerKw = 357, PowertrainLayout = "RWD", TorqueNm = 392, Transmission = "6-Speed Sequential", VehicleClass = "JP2", WeightKg = 1120, Year = 2003 },
        new() { EngineDisplacementLitres = 3.8, EngineLayout = "Front Engine", EngineType = "L6", FuelCapacityLitres = null, GameId = "ID_Jaguar_E-Type_Lightweight_1964", IconFileName = "Jaguar", Id = "Jaguar_E-Type_Lightweight_1964", Manufacturer = "Jaguar", Name = "E-Type Lightweight", PowerKw = 253, PowertrainLayout = "RWD", TorqueNm = 380, Transmission = "5-Speed Manual", VehicleClass = "GT 60", WeightKg = 1010, Year = 1964 },
        new() { EngineDisplacementLitres = 7, EngineLayout = "Mid Engine", EngineType = "V12", FuelCapacityLitres = 100, GameId = "ID_Jaguar_XJR-9", IconFileName = "Jaguar", Id = "Jaguar_XJR-9_1990", Manufacturer = "Jaguar", Name = "XJR-9", PowerKw = 559, PowertrainLayout = "RWD", TorqueNm = 828, Transmission = "5-Speed Manual", VehicleClass = "Group C", WeightKg = 880, Year = 1990 },
        new() { EngineDisplacementLitres = 5.2, EngineLayout = "Mid Engine", EngineType = "V10", FuelCapacityLitres = 90.6, GameId = "ID_Lamborghini_Huracan_GT3_Evo_2022", IconFileName = "Lamborghini", Id = "Lamborghini_Huracán_GT3_Evo2_2022", Manufacturer = "Lamborghini", Name = "Huracán GT3 Evo2", PowerKw = 384, PowertrainLayout = "RWD", TorqueNm = 580, Transmission = "6-Speed Paddle", VehicleClass = "GT3", WeightKg = 1280, Year = 2022 },
        new() { EngineDisplacementLitres = 6, EngineLayout = "Mid Engine", EngineType = "V12", FuelCapacityLitres = 75.5, GameId = "ID_Lamborghini_Murcielago_R-GT_2004", IconFileName = "Lamborghini", Id = "Lamborghini_Murcielago_R-GT_2004", Manufacturer = "Lamborghini", Name = "Murcielago R-GT", PowerKw = 447, PowertrainLayout = "RWD", TorqueNm = 650, Transmission = "6-Speed Sequential", VehicleClass = "GT", WeightKg = 1100, Year = 2004 },
        new() { EngineDisplacementLitres = 3.8, EngineLayout = "Mid Engine", EngineType = "V8 Twin Turbo", FuelCapacityLitres = null, GameId = "ID_Lamborghini_SC63_LMDh_2024", IconFileName = "Lamborghini", Id = "Lamborghini_SC63_LMDh_2024", Manufacturer = "Lamborghini", Name = "SC63 LMDh", PowerKw = 499, PowertrainLayout = "RWD", TorqueNm = 710, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", WeightKg = 1030, Year = 2024 },
        new() { EngineDisplacementLitres = 7, EngineLayout = "Front Engine", EngineType = "V12", FuelCapacityLitres = 75.5, GameId = "ID_Lister_Storm_GT", IconFileName = "Lister", Id = "Lister_Storm_GT_2004", Manufacturer = "Lister", Name = "Storm GT", PowerKw = 428, PowertrainLayout = "RWD", TorqueNm = 780, Transmission = "6-Speed Sequential", VehicleClass = "GT", WeightKg = 1125, Year = 2004 },
        new() { EngineDisplacementLitres = 5.9, EngineLayout = "Mid Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Lola_T70_MK3_67", IconFileName = "Lola", Id = "Lola_T70_Mk3_1967", Manufacturer = "Lola", Name = "T70 Mk3", PowerKw = 365, PowertrainLayout = "RWD", TorqueNm = 520, Transmission = "4-Speed Manual", VehicleClass = "Sports Car 67", WeightKg = 865, Year = 1967 },
        new() { EngineDisplacementLitres = 5, EngineLayout = "Mid Engine", EngineType = "V8", FuelCapacityLitres = 120, GameId = "ID_Lola_T70_MK3B_1970", IconFileName = "Lola", Id = "Lola_T70_Mk3B_GT_1970", Manufacturer = "Lola", Name = "T70 Mk3B GT", PowerKw = 335, PowertrainLayout = "RWD", TorqueNm = 485, Transmission = "5-Speed Manual", VehicleClass = "Sports Car 70", WeightKg = 845, Year = 1970 },
        new() { EngineDisplacementLitres = 6, EngineLayout = "Mid Engine", EngineType = "V8", FuelCapacityLitres = 100, GameId = "ID_Lotus_Elise_GT1_1997", IconFileName = "Lotus", Id = "Lotus_Elise_GT1_1997", Manufacturer = "Lotus", Name = "Elise GT1", PowerKw = 428, PowertrainLayout = "RWD", TorqueNm = 625, Transmission = "6-Speed Sequential", VehicleClass = "GT1", WeightKg = 972, Year = 1997 },
        new() { EngineDisplacementLitres = 6, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = 75.5, GameId = "ID_Marcos_Mantara_LM600_GT2_2004", IconFileName = "Marcos", Id = "Marcos_Mantara_LM600_2004", Manufacturer = "Marcos", Name = "Mantara LM600", PowerKw = 357, PowertrainLayout = "RWD", TorqueNm = 650, Transmission = "6-Speed Sequential", VehicleClass = "N-GT", WeightKg = 1150, Year = 2004 },
        new() { EngineDisplacementLitres = 6, EngineLayout = "Mid Engine", EngineType = "V12", FuelCapacityLitres = 75.5, GameId = "ID_Maserati_MC12_GT1", IconFileName = "Maserati", Id = "Maserati_MC12_GT1_2004", Manufacturer = "Maserati", Name = "MC12 GT1", PowerKw = 432, PowertrainLayout = "RWD", TorqueNm = 600, Transmission = "6-Speed Sequential", VehicleClass = "GT", WeightKg = 1100, Year = 2004 },
        new() { EngineDisplacementLitres = 2.6, EngineLayout = "Mid Engine", EngineType = "4-Rotor", FuelCapacityLitres = 100, GameId = "ID_Mazda_787B_1991", IconFileName = "Mazda", Id = "Mazda_787B_1991", Manufacturer = "Mazda", Name = "787B", PowerKw = 521, PowertrainLayout = "RWD", TorqueNm = 608, Transmission = "5-Speed Manual", VehicleClass = "Group C", WeightKg = 830, Year = 1991 },
        new() { EngineDisplacementLitres = 2, EngineLayout = "Front Engine", EngineType = "L4", FuelCapacityLitres = 34, GameId = "ID_Mazda_MX-5_Cup_2017", IconFileName = "Mazda", Id = "Mazda_MX-5_Spec_2017", Manufacturer = "Mazda", Name = "MX-5 Spec", PowerKw = 126, PowertrainLayout = "RWD", TorqueNm = 204, Transmission = "6-Speed Manual", VehicleClass = "MX5 Trophy", WeightKg = 1095, Year = 2017 },
        new() { EngineDisplacementLitres = 2.6, EngineLayout = "Front Engine", EngineType = "4-Rotor", FuelCapacityLitres = 75.5, GameId = "ID_MAZDA_RX-7_GTO_1989", IconFileName = "Mazda", Id = "Mazda_RX-7_GTO_1989", Manufacturer = "Mazda", Name = "RX-7 GTO", PowerKw = 447, PowertrainLayout = "RWD", TorqueNm = 530, Transmission = "5-Speed Manual", VehicleClass = "GTO", WeightKg = 1020, Year = 1989 },
        new() { EngineDisplacementLitres = 6.3, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = 90.6, GameId = "ID_Mercedes_AMG_GT3_Evo", IconFileName = "Mercedes", Id = "Mercedes-AMG_GT3_2020", Manufacturer = "Mercedes-AMG", Name = "GT3", PowerKw = 387, PowertrainLayout = "RWD", TorqueNm = 625, Transmission = "6-Speed Paddle", VehicleClass = "GT3", WeightKg = 1325, Year = 2020 },
        new() { EngineDisplacementLitres = 4, EngineLayout = "Front Engine", EngineType = "V8 Twin Turbo", FuelCapacityLitres = 120, GameId = "ID_Mercedes_AMG_GT4", IconFileName = "Mercedes", Id = "Mercedes-AMG_GT4_2020", Manufacturer = "Mercedes-AMG", Name = "GT4", PowerKw = 350, PowertrainLayout = "RWD", TorqueNm = 580, Transmission = "6-Speed Paddle", VehicleClass = "GT4", WeightKg = 1390, Year = 2020 },
        new() { EngineDisplacementLitres = 5, EngineLayout = "Mid Engine", EngineType = "V8", FuelCapacityLitres = 100, GameId = "ID_Mercedes_CLK-LM_1998", IconFileName = "Mercedes", Id = "Mercedes-Benz_CLK-LM_1998", Manufacturer = "Mercedes-Benz", Name = "CLK-LM", PowerKw = 447, PowertrainLayout = "RWD", TorqueNm = 685, Transmission = "6-Speed Sequential", VehicleClass = "GT1", WeightKg = 971, Year = 1998 },
        new() { EngineDisplacementLitres = 5, EngineLayout = "Mid Engine", EngineType = "V8 Twin Turbo", FuelCapacityLitres = 100, GameId = "ID_Sauber_C9_1989", IconFileName = "Mercedes", Id = "Mercedes-Benz_Sauber_C9_1989", Manufacturer = "Mercedes-Benz", Name = "Sauber C9", PowerKw = 611, PowertrainLayout = "RWD", TorqueNm = 922, Transmission = "5-Speed Manual", VehicleClass = "Group C", WeightKg = 905, Year = 1989 },
        new() { EngineDisplacementLitres = 5.5, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = 75.5, GameId = "ID_Mercury_Cougar_XR-7_GTO_1989", IconFileName = "Mercury", Id = "Mercury_Cougar_XR-7_GTO_1989", Manufacturer = "Mercury", Name = "Cougar XR-7 GTO", PowerKw = 503, PowertrainLayout = "RWD", TorqueNm = 660, Transmission = "5-Speed Manual", VehicleClass = "GTO", WeightKg = 1175, Year = 1989 },
        new() { EngineDisplacementLitres = 4.6, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = 75.5, GameId = "ID_Morgan_Aero_8_GTN", IconFileName = "Morgan", Id = "Morgan_Aero_8_GT(N)_2004", Manufacturer = "Morgan", Name = "Aero 8 GT(N)", PowerKw = 305, PowertrainLayout = "RWD", TorqueNm = 500, Transmission = "6-Speed Sequential", VehicleClass = "N-GT", WeightKg = 1010, Year = 2004 },
        new() { EngineDisplacementLitres = 5.7, EngineLayout = "Mid Engine", EngineType = "V8", FuelCapacityLitres = 90, GameId = "ID_Mosler_MT900R", IconFileName = "Mosler", Id = "Mosler_MT900R_2004", Manufacturer = "Mosler", Name = "MT900R", PowerKw = 335, PowertrainLayout = "RWD", TorqueNm = 425, Transmission = "6-Speed Sequential", VehicleClass = "N-GT", WeightKg = 1100, Year = 2004 },
        new() { EngineDisplacementLitres = 3, EngineLayout = "Front Engine", EngineType = "V6 Turbo", FuelCapacityLitres = 75.5, GameId = "ID_Nissan_300ZX_IMSA_GTO_1989", IconFileName = "Nissan", Id = "Nissan_300ZX_Turbo_GTO_1989", Manufacturer = "Nissan", Name = "300ZX Turbo GTO", PowerKw = 559, PowertrainLayout = "RWD", TorqueNm = 850, Transmission = "5-Speed Manual", VehicleClass = "GTO", WeightKg = 1225, Year = 1989 },
        new() { EngineDisplacementLitres = 2, EngineLayout = "Front Engine", EngineType = "L4 Turbo", FuelCapacityLitres = null, GameId = "ID_Nissan_Z_GT500", IconFileName = "Nissan", Id = "Nissan_Calsonic_Impul_Z_JP1_2022", Manufacturer = "Nissan", Name = "Calsonic Impul Z JP1", PowerKw = 404, PowertrainLayout = "RWD", TorqueNm = 490, Transmission = "6-Speed Paddle", VehicleClass = "JP1", WeightKg = 1020, Year = 2022 },
        new() { EngineDisplacementLitres = 4.2, EngineLayout = "Front Engine", EngineType = "V8 Twin Turbo", FuelCapacityLitres = null, GameId = "ID_Nissan_280ZX_IMSA", IconFileName = "Nissan", Id = "Nissan_Datsun_280_ZX_Turbo_1981", Manufacturer = "Nissan", Name = "Datsun 280 ZX Turbo", PowerKw = 573, PowertrainLayout = "RWD", TorqueNm = 1060, Transmission = "5-Speed Manual", VehicleClass = "Group 5", WeightKg = 1167, Year = 1981 },
        new() { EngineDisplacementLitres = 3, EngineLayout = "Front Engine", EngineType = "V6 Turbo", FuelCapacityLitres = null, GameId = "ID_NISSAN_350Z_GT500_2004", IconFileName = "Nissan", Id = "Nissan_Fairlady_Z_(Z33)_JP2_2004", Manufacturer = "Nissan", Name = "Fairlady Z (Z33) JP2", PowerKw = 346, PowertrainLayout = "RWD", TorqueNm = 706, Transmission = "6-Speed Sequential", VehicleClass = "JP2", WeightKg = 1080, Year = 2004 },
        new() { EngineDisplacementLitres = 2, EngineLayout = "Front Engine", EngineType = "L4 Turbo", FuelCapacityLitres = null, GameId = "ID_Nissan_GTR_R35_GT500", IconFileName = "Nissan", Id = "Nissan_Motul_Autech_GT-R_JP1_2021", Manufacturer = "Nissan", Name = "Motul Autech GT-R JP1", PowerKw = 404, PowertrainLayout = "RWD", TorqueNm = 490, Transmission = "6-Speed Paddle", VehicleClass = "JP1", WeightKg = 1020, Year = 2021 },
        new() { EngineDisplacementLitres = 3.5, EngineLayout = "Mid Engine", EngineType = "V8 Twin Turbo", FuelCapacityLitres = 100, GameId = "ID_Nissan_R390_GT1", IconFileName = "Nissan", Id = "Nissan_R390_GT1_1998", Manufacturer = "Nissan", Name = "R390 GT1", PowerKw = 478, PowertrainLayout = "RWD", TorqueNm = 706, Transmission = "6-Speed Sequential", VehicleClass = "GT1", WeightKg = 1000, Year = 1998 },
        new() { EngineDisplacementLitres = 3.5, EngineLayout = "Mid Engine", EngineType = "V8 Twin Turbo", FuelCapacityLitres = 100, GameId = "ID_Nissan_R89C", IconFileName = "Nissan", Id = "Nissan_R89C_1989", Manufacturer = "Nissan", Name = "R89C", PowerKw = 588, PowertrainLayout = "RWD", TorqueNm = 784, Transmission = "5-Speed Manual", VehicleClass = "Group C", WeightKg = 900, Year = 1989 },
        new() { EngineDisplacementLitres = 3, EngineLayout = "Front Engine", EngineType = "V6 Twin Turbo", FuelCapacityLitres = null, GameId = "ID_Nissan_GT-R_R34_JGTC_2003", IconFileName = "Nissan", Id = "Nissan_Skyline_GT-R_(R34)_JP2_2003", Manufacturer = "Nissan", Name = "Skyline GT-R (R34) JP2", PowerKw = 356, PowertrainLayout = "RWD", TorqueNm = 735, Transmission = "6-Speed Sequential", VehicleClass = "JP2", WeightKg = 1080, Year = 2003 },
        new() { EngineDisplacementLitres = 2.1, EngineLayout = "Front Engine", EngineType = "L4 Turbo", FuelCapacityLitres = null, GameId = "ID_Nissan_Skyline_KDR30", IconFileName = "Nissan", Id = "Nissan_Skyline_Super_Silhouette_1983", Manufacturer = "Nissan", Name = "Skyline Super Silhouette", PowerKw = 425, PowertrainLayout = "RWD", TorqueNm = 545, Transmission = "5-Speed Manual", VehicleClass = "Group 5", WeightKg = 1005, Year = 1983 },
        new() { EngineDisplacementLitres = 3, EngineLayout = "Front Engine", EngineType = "V6", FuelCapacityLitres = 120, GameId = "ID_Nissan_Z_GT4_2023", IconFileName = "Nissan", Id = "Nissan_Z_GT4_2023", Manufacturer = "Nissan", Name = "Z GT4", PowerKw = 328, PowertrainLayout = "RWD", TorqueNm = 600, Transmission = "6-Speed Paddle", VehicleClass = "GT4", WeightKg = 1460, Year = 2023 },
        new() { EngineDisplacementLitres = 6, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = 100, GameId = "ID_PANOZ_ESPERANTE_GTR1", IconFileName = "Panoz", Id = "Panoz_Esperante_GTR-1_1998", Manufacturer = "Panoz", Name = "Esperante GTR-1", PowerKw = 445, PowertrainLayout = "RWD", TorqueNm = 670, Transmission = "6-Speed Sequential", VehicleClass = "GT1", WeightKg = 960, Year = 1998 },
        new() { EngineDisplacementLitres = 6, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = 90, GameId = "ID_Panoz_LMP1_Roadster_S_99", IconFileName = "Panoz", Id = "Panoz_LMP1_Roadster_S_1999", Manufacturer = "Panoz", Name = "LMP1 Roadster S", PowerKw = 469, PowertrainLayout = "RWD", TorqueNm = 670, Transmission = "6-Speed Sequential", VehicleClass = "LMP", WeightKg = 905, Year = 1999 },
        new() { EngineDisplacementLitres = 2.6, EngineLayout = "Mid Engine", EngineType = "V6 Twin Turbo", FuelCapacityLitres = null, GameId = "ID_Peugeot_9X8_2024", IconFileName = "Peugeot", Id = "Peugeot_9X8_2024", Manufacturer = "Peugeot", Name = "9X8", PowerKw = 499, PowertrainLayout = "RWD", TorqueNm = 670, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", WeightKg = 1030, Year = 2024 },
        new() { EngineDisplacementLitres = 5, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Plymouth_Barracuda_Trans_Am_1970", IconFileName = "Plymouth", Id = "Plymouth_Barracuda_1970", Manufacturer = "Plymouth", Name = "Barracuda", PowerKw = 339, PowertrainLayout = "RWD", TorqueNm = 470, Transmission = "4-Speed Manual", VehicleClass = "Historic USV8", WeightKg = 1390, Year = 1970 },
        new() { EngineDisplacementLitres = 4, EngineLayout = "Mid Engine", EngineType = "Flat-6", FuelCapacityLitres = 115, GameId = "ID_Porsche_Cayman_GT4_Clubsport_2022", IconFileName = "Porsche", Id = "Porsche_718_Cayman_GT4_Clubsport_2020", Manufacturer = "Porsche", Name = "718 Cayman GT4 Clubsport", PowerKw = 320, PowertrainLayout = "RWD", TorqueNm = 420, Transmission = "7-Speed Paddle", VehicleClass = "GT4", WeightKg = 1420, Year = 2020 },
        new() { EngineDisplacementLitres = 3.6, EngineLayout = "Rear Engine", EngineType = "Flat-6", FuelCapacityLitres = 100, GameId = "ID_Porsche_Carrera_Cup", IconFileName = "Porsche", Id = "Porsche_911_Carrera_Cup_(964)_1990", Manufacturer = "Porsche", Name = "911 Carrera Cup (964)", PowerKw = 194, PowertrainLayout = "RWD", TorqueNm = 310, Transmission = "5-Speed Manual", VehicleClass = "964 Trophy", WeightKg = 1120, Year = 1990 },
        new() { EngineDisplacementLitres = 3, EngineLayout = "Rear Engine", EngineType = "Flat-6", FuelCapacityLitres = null, GameId = "ID_Porsche_911_RSR_1974", IconFileName = "Porsche", Id = "Porsche_911_Carrera_RSR_3.0_1974", Manufacturer = "Porsche", Name = "911 Carrera RSR 3.0", PowerKw = 246, PowertrainLayout = "RWD", TorqueNm = 315, Transmission = "5-Speed Manual", VehicleClass = "GT 70", WeightKg = 900, Year = 1974 },
        new() { EngineDisplacementLitres = 3.2, EngineLayout = "Mid Engine", EngineType = "Flat-6", FuelCapacityLitres = 100, GameId = "ID_Porsche_911_GT1_98", IconFileName = "Porsche", Id = "Porsche_911_GT1-98_1998", Manufacturer = "Porsche", Name = "911 GT1-98", PowerKw = 432, PowertrainLayout = "RWD", TorqueNm = 630, Transmission = "6-Speed Sequential", VehicleClass = "GT1", WeightKg = 967, Year = 1998 },
        new() { EngineDisplacementLitres = 4, EngineLayout = "Rear Engine", EngineType = "Flat-6", FuelCapacityLitres = 75.5, GameId = "ID_Porsche_911_GT3_Cup_2022", IconFileName = "Porsche", Id = "Porsche_911_GT3_Cup_(992)_2024", Manufacturer = "Porsche", Name = "911 GT3 Cup (992)", PowerKw = 375, PowertrainLayout = "RWD", TorqueNm = 470, Transmission = "6-Speed Paddle", VehicleClass = "992 Trophy", WeightKg = 1260, Year = 2024 },
        new() { EngineDisplacementLitres = 4.2, EngineLayout = "Rear Engine", EngineType = "Flat-6", FuelCapacityLitres = 90.6, GameId = "ID_Porsche_992_GT3R", IconFileName = "Porsche", Id = "Porsche_911_GT3_R_(992)_2023", Manufacturer = "Porsche", Name = "911 GT3 R (992)", PowerKw = 421, PowertrainLayout = "RWD", TorqueNm = 560, Transmission = "6-Speed Paddle", VehicleClass = "GT3", WeightKg = 1325, Year = 2023 },
        new() { EngineDisplacementLitres = 3.6, EngineLayout = "Rear Engine", EngineType = "Flat-6", FuelCapacityLitres = 67.5, GameId = "ID_Porsche_911_GT3-RSR_2004", IconFileName = "Porsche", Id = "Porsche_911_GT3-RSR_(996)_2004", Manufacturer = "Porsche", Name = "911 GT3-RSR (996)", PowerKw = 335, PowertrainLayout = "RWD", TorqueNm = 405, Transmission = "6-Speed Sequential", VehicleClass = "N-GT", WeightKg = 1125, Year = 2004 },
        new() { EngineDisplacementLitres = 4, EngineLayout = "Mid Engine", EngineType = "Flat-6", FuelCapacityLitres = null, GameId = "ID_Porsche_911_RSR_GTE_2020", IconFileName = "Porsche", Id = "Porsche_911_RSR_GTE_2020", Manufacturer = "Porsche", Name = "911 RSR GTE", PowerKw = 384, PowertrainLayout = "RWD", TorqueNm = 490, Transmission = "6-Speed Paddle", VehicleClass = "GTE", WeightKg = 1235, Year = 2020 },
        new() { EngineDisplacementLitres = 4.5, EngineLayout = "Mid Engine", EngineType = "Flat-12", FuelCapacityLitres = 120, GameId = "ID_Porsche_917K_1970", IconFileName = "Porsche", Id = "Porsche_917K_1970", Manufacturer = "Porsche", Name = "917K", PowerKw = 387, PowertrainLayout = "RWD", TorqueNm = 490, Transmission = "5-Speed Manual", VehicleClass = "Sports Car 70", WeightKg = 840, Year = 1970 },
        new() { EngineDisplacementLitres = 2.8, EngineLayout = "Rear Engine", EngineType = "Flat-6 Turbo", FuelCapacityLitres = null, GameId = "ID_Porsche_935_80", IconFileName = "Porsche", Id = "Porsche_935/80_1979", Manufacturer = "Porsche", Name = "935/80", PowerKw = 596, PowertrainLayout = "RWD", TorqueNm = 780, Transmission = "4-Speed Manual", VehicleClass = "Group 5", WeightKg = 1110, Year = 1979 },
        new() { EngineDisplacementLitres = 2.8, EngineLayout = "Mid Engine", EngineType = "Flat-6 Turbo", FuelCapacityLitres = 100, GameId = "ID_Porsche_962C_88", IconFileName = "Porsche", Id = "Porsche_962C_1988", Manufacturer = "Porsche", Name = "962C", PowerKw = 581, PowertrainLayout = "RWD", TorqueNm = 710, Transmission = "5-Speed Manual", VehicleClass = "Group C", WeightKg = 871, Year = 1988 },
        new() { EngineDisplacementLitres = 4.6, EngineLayout = "Mid Engine", EngineType = "V8 Twin Turbo", FuelCapacityLitres = null, GameId = "ID_Porsche_963", IconFileName = "Porsche", Id = "Porsche_963_2023", Manufacturer = "Porsche", Name = "963", PowerKw = 499, PowertrainLayout = "RWD", TorqueNm = 710, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", WeightKg = 1030, Year = 2023 },
        new() { EngineDisplacementLitres = 7, EngineLayout = "Mid Engine", EngineType = "V8", FuelCapacityLitres = 75.5, GameId = "ID_Saleen_S7R", IconFileName = "Saleen", Id = "Saleen_S7R_2004", Manufacturer = "Saleen", Name = "S7R", PowerKw = 447, PowertrainLayout = "RWD", TorqueNm = 746, Transmission = "6-Speed Sequential", VehicleClass = "GT", WeightKg = 1150, Year = 2004 },
        new() { EngineDisplacementLitres = 4.7, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Shelby_Daytona_Coupe_1964", IconFileName = "Shelby", Id = "Shelby_Daytona_Coupe_1964", Manufacturer = "Shelby", Name = "Daytona Coupe", PowerKw = 290, PowertrainLayout = "RWD", TorqueNm = 462, Transmission = "4-Speed Manual", VehicleClass = "GT 60", WeightKg = 1043, Year = 1964 },
        new() { EngineDisplacementLitres = 3, EngineLayout = "Front Engine", EngineType = "L6 Twin Turbo", FuelCapacityLitres = 120, GameId = "ID_Toyota_Supra_GT4", IconFileName = "Toyota", Id = "Toyota_GR_Supra_GT4_EVO_2023", Manufacturer = "Toyota", Name = "GR Supra GT4 EVO", PowerKw = 320, PowertrainLayout = "RWD", TorqueNm = 585, Transmission = "6-Speed Paddle", VehicleClass = "GT4", WeightKg = 1370, Year = 2023 },
        new() { EngineDisplacementLitres = 2, EngineLayout = "Front Engine", EngineType = "L4 Turbo", FuelCapacityLitres = null, GameId = "ID_Toyota_GR_Supra_GT500", IconFileName = "Toyota", Id = "Toyota_GR_Supra_JP1_2022", Manufacturer = "Toyota", Name = "GR Supra JP1", PowerKw = 404, PowertrainLayout = "RWD", TorqueNm = 490, Transmission = "6-Speed Paddle", VehicleClass = "JP1", WeightKg = 1020, Year = 2022 },
        new() { EngineDisplacementLitres = 3.5, EngineLayout = "Mid Engine", EngineType = "V6 Twin Turbo", FuelCapacityLitres = null, GameId = "ID_Toyota_GR010", IconFileName = "Toyota", Id = "Toyota_GR010_Hybrid_2023", Manufacturer = "Toyota", Name = "GR010 Hybrid", PowerKw = 499, PowertrainLayout = "RWD", TorqueNm = 740, Transmission = "7-Speed Paddle", VehicleClass = "LMDh", WeightKg = 1030, Year = 2023 },
        new() { EngineDisplacementLitres = 3.6, EngineLayout = "Mid Engine", EngineType = "V8", FuelCapacityLitres = 100, GameId = "ID_Toyota_GT-One_TS020", IconFileName = "Toyota", Id = "Toyota_GT-One_1998", Manufacturer = "Toyota", Name = "GT-One", PowerKw = 447, PowertrainLayout = "RWD", TorqueNm = 650, Transmission = "6-Speed Sequential", VehicleClass = "GT1", WeightKg = 921, Year = 1998 },
        new() { EngineDisplacementLitres = 5.2, EngineLayout = "Front Engine", EngineType = "V8", FuelCapacityLitres = null, GameId = "ID_Toyota_Supra_JGTC_2003", IconFileName = "Toyota", Id = "Toyota_Supra_JP2_2003", Manufacturer = "Toyota", Name = "Supra JP2", PowerKw = 372, PowertrainLayout = "RWD", TorqueNm = 588, Transmission = "6-Speed Sequential", VehicleClass = "JP2", WeightKg = 1100, Year = 2003 },
        new() { EngineDisplacementLitres = 4, EngineLayout = "Front Engine", EngineType = "L6", FuelCapacityLitres = 67.5, GameId = "ID_TVR_TUSCAN_T400R_2002", IconFileName = "TVR", Id = "TVR_Tuscan_T400R_2004", Manufacturer = "TVR", Name = "Tuscan T400R", PowerKw = 290, PowertrainLayout = "RWD", TorqueNm = 420, Transmission = "6-Speed Sequential", VehicleClass = "N-GT", WeightKg = 1100, Year = 2004 },
    ];

    public static PmrCarInfoProvider Instance => singletonInstance ??= new PmrCarInfoProvider();

    public PmrCarInfo? FindByGameId(string gameId)
    {
        return this.cars.FirstOrDefault(
            c => string.Equals(c.GameId, gameId, StringComparison.OrdinalIgnoreCase));
    }

    public PmrCarInfo? FindById(string id)
    {
        return this.cars.FirstOrDefault(c => c.Id == id);
    }

    public IReadOnlyCollection<PmrCarInfo> GetCarInfos()
    {
        return this.cars.AsReadOnly();
    }

    public IReadOnlyCollection<PmrCarInfo> GetCarInfosForManufacturer(string manufacturer)
    {
        return this.cars.Where(c => c.Manufacturer == manufacturer)
                         .ToList()
                         .AsReadOnly();
    }

    public IReadOnlyCollection<string> GetManufacturers()
    {
        return this.cars.Select(c => c.Manufacturer)
                         .Distinct()
                         .OrderBy(m => m)
                         .ToList()
                         .AsReadOnly();
    }
}
